{
  "hash": "c13d34486915bb3926db9b09102915a4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nformat: html\njupyter: python3\nexecute:\n  echo: true\n  error: false\n  warning: true\n  freeze: auto\ntitle: Demographic table\ndescription: Summarise age, sex and race by treatment arm in polars\nnav: Demographic table\norder: 2\nbread-crumbs: false\n---\n\nThe subject demographics table every ADaM deliverable carries: age and its groups, sex\nand race, summarised by treatment arm, built from `pharmadata.pharmaverseadam.adsl` in\npolars. It copies the target table of the\n[R demographic table example](https://pharmaverse.github.io/examples/tlg/demographic.html),\nwhich does the same with {cards} and {gtsummary}.\n\nThe blocks run as the page is rendered, and the table is printed by the code rather than\nwritten into the page.\n\n::: {#77b86ab3 .cell execution_count=1}\n``` {.python .cell-code}\nimport polars as pl\n\nfrom pharmadata import pharmaverseadam as adam\n```\n:::\n\n\n## The population\n\nThe analysis population is the 254 subjects who were randomised and treated; screen\nfailures stay out of the table. The two recodes are display spellings only.\n\n::: {#b3991413 .cell execution_count=2}\n``` {.python .cell-code}\nARMS = [\"Placebo\", \"Xanomeline High Dose\", \"Xanomeline Low Dose\"]\n\nadsl = adam.adsl.filter(pl.col(\"ACTARM\") != \"Screen Failure\").with_columns(\n    pl.col(\"SEX\").replace_strict({\"M\": \"MALE\", \"F\": \"FEMALE\"}),\n    pl.when(pl.col(\"AGE\").is_between(18, 40))\n    .then(pl.lit(\"18-40\"))\n    .when(pl.col(\"AGE\").is_between(41, 64))\n    .then(pl.lit(\"41-64\"))\n    .when(pl.col(\"AGE\") > 64)\n    .then(pl.lit(\">=65\"))\n    .alias(\"AGEGR1\"),\n)\n```\n:::\n\n\n## Statistics as rows\n\nA long frame worn as a wide one: one row per statistic, per arm. Two functions produce\nthose rows, one for a numeric variable and one for a categorical, and a third names a\nblock.\n\n::: {#589e9712 .cell execution_count=3}\n``` {.python .cell-code}\ndef group(label: str) -> pl.DataFrame:\n    \"\"\"The bold row that opens a block of characteristics.\"\"\"\n    return pl.DataFrame({\"ACTARM\": [\"\"], \"label\": [f\"**{label}**\"], \"value\": [\"\"]})\n\n\ndef one_decimal(column: str) -> pl.Expr:\n    return pl.col(column).round(1).cast(pl.String)\n\n\ndef summarise(df: pl.DataFrame, variable: str) -> pl.DataFrame:\n    \"\"\"N, Mean (SD), Median (Q1, Q3) and Min, Max of one numeric variable, by arm.\"\"\"\n    return (\n        df.group_by(\"ACTARM\", maintain_order=True)\n        .agg(\n            pl.col(variable).count().alias(\"N\"),\n            pl.col(variable).mean().alias(\"mean\"),\n            pl.col(variable).std().alias(\"sd\"),\n            pl.col(variable).median().alias(\"median\"),\n            pl.col(variable).quantile(0.25, interpolation=\"linear\").alias(\"q1\"),\n            pl.col(variable).quantile(0.75, interpolation=\"linear\").alias(\"q3\"),\n            pl.col(variable).min().alias(\"low\"),\n            pl.col(variable).max().alias(\"high\"),\n        )\n        .select(\n            \"ACTARM\",\n            pl.col(\"N\").cast(pl.String),\n            pl.concat_str(\n                [one_decimal(\"mean\"), pl.lit(\" (\"), one_decimal(\"sd\"), pl.lit(\")\")]\n            ).alias(\"Mean (SD)\"),\n            pl.concat_str(\n                [\n                    one_decimal(\"median\"),\n                    pl.lit(\" (\"),\n                    one_decimal(\"q1\"),\n                    pl.lit(\", \"),\n                    one_decimal(\"q3\"),\n                    pl.lit(\")\"),\n                ]\n            ).alias(\"Median (Q1, Q3)\"),\n            pl.concat_str(\n                [one_decimal(\"low\"), pl.lit(\", \"), one_decimal(\"high\")]\n            ).alias(\"Min, Max\"),\n        )\n        .unpivot(index=\"ACTARM\", variable_name=\"label\", value_name=\"value\")\n    )\n```\n:::\n\n\nThe `unpivot` turns the four formatted statistics into four rows. A name given with\n`alias()` becomes the row's label, so the display strings are built before it.\n\n::: {#d003e532 .cell execution_count=4}\n``` {.python .cell-code}\ndef counts(df: pl.DataFrame, variable: str, levels: list[str]) -> pl.DataFrame:\n    \"\"\"n (%) at each level of one categorical variable, by arm.\"\"\"\n    return (\n        pl.DataFrame({\"ACTARM\": ARMS})\n        .join(pl.DataFrame({variable: levels}), how=\"cross\")\n        .join(\n            df.group_by(\"ACTARM\", variable).len(name=\"n\"),\n            on=[\"ACTARM\", variable],\n            how=\"left\",\n        )\n        .with_columns(pl.col(\"n\").fill_null(0))\n        .join(df.group_by(\"ACTARM\").len(name=\"N\"), on=\"ACTARM\")\n        .select(\n            \"ACTARM\",\n            pl.col(variable).alias(\"label\"),\n            pl.concat_str(\n                [\n                    pl.col(\"n\").cast(pl.String),\n                    pl.lit(\" (\"),\n                    (100 * pl.col(\"n\") / pl.col(\"N\")).round(1).cast(pl.String),\n                    pl.lit(\"%)\"),\n                ]\n            ).alias(\"value\"),\n        )\n    )\n```\n:::\n\n\nThe cross join is the point of that first line. No subject is between 18 and 40, so a\n`group_by` would drop the level silently; the levels are part of the specification, so\nthey are listed and counts are joined onto them.\n\n## Assemble, then pivot\n\n::: {#43eb6553 .cell execution_count=5}\n``` {.python .cell-code}\nlong = pl.concat(\n    [\n        group(\"Age (yr)\"),\n        summarise(adsl, \"AGE\"),\n        group(\"Age group\"),\n        counts(adsl, \"AGEGR1\", [\"18-40\", \"41-64\", \">=65\"]),\n        group(\"Sex\"),\n        counts(adsl, \"SEX\", [\"FEMALE\", \"MALE\"]),\n        group(\"Race\"),\n        counts(\n            adsl,\n            \"RACE\",\n            [\"AMERICAN INDIAN OR ALASKA NATIVE\", \"BLACK OR AFRICAN AMERICAN\", \"WHITE\"],\n        ),\n    ]\n)\n```\n:::\n\n\n`pivot()` puts an arm in each column. It does not promise a row order, so the order of\nfirst appearance is captured before the pivot and joined back after it.\n\n::: {#1e2ce50a .cell execution_count=6}\n``` {.python .cell-code}\norder = (\n    long.get_column(\"label\")\n    .unique(maintain_order=True)\n    .to_frame()\n    .with_columns(pl.int_range(pl.len()).alias(\"ord\"))\n)\n\ntlf = (\n    long.pivot(index=\"label\", on=\"ACTARM\", values=\"value\")\n    .join(order, on=\"label\")\n    .sort(\"ord\")\n    .drop(\"ord\")\n    .rename({\"label\": \"Characteristic\"})\n    .select(\"Characteristic\", *ARMS)\n)\n```\n:::\n\n\n## The table\n\npolars' `_repr_html_` escapes the markdown in the group-row labels, so the page builds a\nmarkdown table by hand and hands it to Quarto with `IPython.display.Markdown`, which\nrenders it as an HTML table and keeps the bold group headers intact.\n\n::: {#bc2507b7 .cell execution_count=7}\n``` {.python .cell-code}\nfrom IPython.display import Markdown, display\n\n\ndef to_markdown(df: pl.DataFrame) -> str:\n    \"\"\"Render a frame as a markdown table.\"\"\"\n    lines = [\n        \"| \" + \" | \".join(df.columns) + \" |\",\n        \"| \" + \" | \".join([\"---\"] * df.width) + \" |\",\n    ]\n    for row in df.iter_rows():\n        cells = [\"\" if value is None else str(value) for value in row]\n        lines.append(\"| \" + \" | \".join(cells) + \" |\")\n    return \"\\n\".join(lines)\n\n\ndisplay(Markdown(to_markdown(tlf)))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Characteristic | Placebo | Xanomeline High Dose | Xanomeline Low Dose |\n| --- | --- | --- | --- |\n| **Age (yr)** |  |  |  |\n| N | 86 | 72 | 96 |\n| Mean (SD) | 75.2 (8.6) | 73.8 (7.9) | 76.0 (8.1) |\n| Median (Q1, Q3) | 76.0 (69.2, 81.8) | 75.5 (70.5, 79.0) | 78.0 (71.0, 82.0) |\n| Min, Max | 52.0, 89.0 | 56.0, 88.0 | 51.0, 88.0 |\n| **Age group** |  |  |  |\n| 18-40 | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n| 41-64 | 14 (16.3%) | 11 (15.3%) | 8 (8.3%) |\n| >=65 | 72 (83.7%) | 61 (84.7%) | 88 (91.7%) |\n| **Sex** |  |  |  |\n| FEMALE | 53 (61.6%) | 35 (48.6%) | 55 (57.3%) |\n| MALE | 33 (38.4%) | 37 (51.4%) | 41 (42.7%) |\n| **Race** |  |  |  |\n| AMERICAN INDIAN OR ALASKA NATIVE | 0 (0.0%) | 1 (1.4%) | 0 (0.0%) |\n| BLACK OR AFRICAN AMERICAN | 8 (9.3%) | 9 (12.5%) | 6 (6.2%) |\n| WHITE | 78 (90.7%) | 62 (86.1%) | 90 (93.8%) |\n:::\n:::\n\n\n## Two things the numbers depend on\n\n**A quartile is a definition, not a value.** polars' `quantile()` defaults to\n`interpolation=\"nearest\"`, which answers with an observed age: on the high-dose arm it\nputs Q1 at 71.0. `linear` is the definition numpy, pandas and R's `quantile(type = 7)`\nshare, and it interpolates, giving 70.5. The R example prints 70.0, because R's own\ndefault is `type = 2`, which averages the two observations instead of interpolating.\n\n**Race has three levels here, not four.** ADSL holds two screen-failure subjects\nrecorded ASIAN, so this population has none. Dropping the population filter is one\nline, and the fourth level appears with it.\n\n",
    "supporting": [
      "demographic-table_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}