"""Package data-raw/raw/ into the shipped parquet and ``_meta.json``.

Data only: this writes ``src/pharmadata/_data/<collection>/`` (the labelled
parquet plus its ``_meta.json``). The collection modules and their ``.pyi``
stubs are generated by ``data-raw/04_build_modules.py`` (run it with
``python data-raw/04_build_modules.py``), and the docs pages by
``data-raw/05_build_dataset_qmd.py``. The descriptive metadata that turns a
``_data`` directory into a collection lives in
``_data/<collection>/_collection.json``; add that file for a new dataset group
and both generators pick it up.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import keyword
from pathlib import Path
from typing import TYPE_CHECKING, Literal, TypedDict, cast

import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq

from pharmadata._core.data import COLLECTIONS, DatasetMetaEntry

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

PKG = Path(__file__).resolve().parents[1]
RAW = PKG / "data-raw" / "raw"
DATA = PKG / "src" / "pharmadata" / "_data"

# The same statement for a reader of the shipped parquet. Durable generator ID
# embedded in every parquet's schema metadata: source file renamed to
# data-raw/03_build_data.py but this string is the persisted identifier read by
# tests and downstream tools, so it stays.
GENERATED_METADATA = {"pharmadata:generator": "data-raw/build_data.py"}


def dtype_name(dtype: pl.DataType) -> str:
    """The CDISC spelling of a polars dtype: base type only, e.g. ``Datetime``."""
    if dtype.base_type() is pl.Datetime:
        return "Datetime"
    if dtype.base_type() is pl.Categorical:
        return "Categorical"
    return str(dtype)


# Columns a *_meta.parquet must carry; `column_type` is written but never read.
META_COLUMNS = (
    "dataset_name",
    "dataset_label",
    "structure",
    "column_name",
    "column_label",
    "mandatory",
    "role",
)


def _validate_name(name: str, path: Path) -> None:
    """A dataset name becomes a Python attribute and a stub line, so it must be one."""
    if not name.isidentifier() or keyword.iskeyword(name):
        msg = f"{path.name}: dataset_name {name!r} is not a valid Python identifier"
        raise ValueError(msg)
    if name.endswith("_meta"):
        msg = (
            f"{path.name}: dataset_name {name!r} ends in '_meta', reserved for "
            "the metadata attribute of another dataset"
        )
        raise ValueError(msg)


class MetaRow(TypedDict):
    """One column's entry in a raw ``*_meta.parquet``."""

    column_label: str | None
    mandatory: str | None
    role: str | None


def _validate_columns(
    meta: pl.DataFrame, path: Path, schema: dict[str, pl.DataType]
) -> dict[str, MetaRow]:
    """Check the metadata rows: unique columns, labels present, matches the data schema."""
    names = meta["column_name"].to_list()
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        msg = f"{path.name}: duplicate column_name rows: {', '.join(dupes)}"
        raise ValueError(msg)
    by_col: dict[str, MetaRow] = {
        record["column_name"]: {
            "column_label": record["column_label"],
            "mandatory": record["mandatory"],
            "role": record["role"],
        }
        for record in meta.iter_rows(named=True)
    }
    for col, row in by_col.items():
        if row["column_label"] is None:
            msg = f"{path.name}: column {col!r} has no label"
            raise ValueError(msg)
    unknown = set(by_col) - set(schema)
    if unknown:
        msg = f"{path.name}: column(s) not in data: {', '.join(sorted(unknown))}"
        raise ValueError(msg)
    uncovered = set(schema) - set(by_col)
    if uncovered:
        msg = f"{path.name}: column(s) missing from metadata: {', '.join(sorted(uncovered))}"
        raise ValueError(msg)
    return by_col


def read_meta(path: Path) -> tuple[str, DatasetMetaEntry]:
    """One *_meta.parquet as a (name, _meta.json entry) pair."""
    meta = pl.read_parquet(path)
    name = _validate_meta_table(meta, path)
    schema = pl.read_parquet_schema(path.with_name(f"{name}.parquet"))
    by_col = _validate_columns(meta, path, schema)
    return name, _build_entry(name, meta, by_col, schema, path)


def _validate_meta_table(meta: pl.DataFrame, path: Path) -> str:
    """Validate the metadata table's shape and names; return the dataset name."""
    if meta.height == 0:
        msg = f"{path.name}: empty metadata table"
        raise ValueError(msg)
    missing = [c for c in META_COLUMNS if c not in meta.columns]
    if missing:
        msg = f"{path.name}: missing metadata column(s): {', '.join(missing)}"
        raise ValueError(msg)
    names = meta["dataset_name"].unique()
    if len(names) != 1:
        msg = f"{path.name}: multiple dataset_name values: {list(names)}"
        raise ValueError(msg)
    name = names[0]
    _validate_name(name, path)
    expected = path.stem.removesuffix("_meta")
    if name != expected:
        msg = (
            f"{path.name}: dataset_name {name!r} does not match file stem {expected!r}"
        )
        raise ValueError(msg)
    return name


def _build_entry(
    name: str,
    meta: pl.DataFrame,
    by_col: dict[str, MetaRow],
    schema: dict[str, pl.DataType],
    path: Path,
) -> DatasetMetaEntry:
    """The ``_meta.json`` entry for one dataset, assembled from its metadata table."""
    return {
        "label": meta["dataset_label"][0],
        "structure": meta["structure"][0],
        # the row count ships in _meta.json, so the runtime never opens the data
        "n_rows": nrows(path.with_name(f"{name}.parquet")),
        "columns": {
            col: {
                "label": by_col[col]["column_label"],
                "type": dtype_name(schema[col]),
                "mandatory": by_col[col]["mandatory"],
                "role": by_col[col]["role"],
            }
            for col in schema
        },
    }


def nrows(path: Path) -> int:
    """Row count of a parquet file, from its footer."""
    return pq.read_metadata(path).num_rows


def embed_labels(frame: pl.DataFrame, entry: DatasetMetaEntry, path: Path) -> None:
    """Rewrite the data parquet with the dataset and column labels in Arrow metadata.

    The schema carries the dataset label; each field carries its column label.
    Richer metadata (type, mandatory, role, structure) stays in ``_meta.json``.
    """
    tbl = frame.to_arrow()
    fields = [
        pa.field(
            name,
            tbl.schema.field(name).type,
            # _validate_columns guarantees a label; the shipped contract types it optional
            metadata={"label": cast("str", entry["columns"][name]["label"])},
        )
        for name in frame.columns
    ]
    schema_metadata = {**GENERATED_METADATA, "label": entry["label"] or ""}
    pq.write_table(tbl.cast(pa.schema(fields, metadata=schema_metadata)), path)


def _parquet_hash(path: Path) -> str:
    """SHA-256 of a parquet file's bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_existing_meta(out_dir: Path) -> dict[str, DatasetMetaEntry]:
    """The shipped ``_meta.json`` if present, else an empty dict."""
    meta_path = out_dir / "_meta.json"
    if not meta_path.is_file():
        return {}
    return json.loads(meta_path.read_text(encoding="utf-8"))


def _update_collection_sources(collection: str, data: Path = DATA) -> None:
    """Copy the fetched source hashes into the shipped ``_collection.json``."""
    sources_path = PKG / "data-raw" / "sources" / collection / "_sources.json"
    coll_path = data / collection / "_collection.json"
    if not sources_path.is_file() or not coll_path.is_file():
        return
    sources = json.loads(sources_path.read_text(encoding="utf-8"))
    coll = json.loads(coll_path.read_text(encoding="utf-8"))
    coll["sources"] = {
        name: {"sha256": entry["sha256"]}
        for name, entry in sources.items()
        if isinstance(entry, dict) and "sha256" in entry
    }
    coll_path.write_text(
        json.dumps(coll, indent=1, ensure_ascii=False),
        encoding="utf-8",
        newline="\n",
    )


def build_collection(
    collection: str,
    only: str | None = None,
    raw: Path = RAW,
    data: Path = DATA,
    changed: set[str] | None = None,
) -> None:
    """Package one collection: the shipped labelled parquet and ``_meta.json``.

    *only* rebuilds one dataset; *changed* limits the rebuild to those dataset
    names (datasets not listed keep their shipped parquet and metadata). When
    *changed* is None every raw dataset is rebuilt. ``_meta.json`` always
    covers the full shipped set: rebuilt entries are merged with the existing
    ones so unchanged datasets are preserved.
    """
    raw_dir, out_dir = raw / collection, data / collection
    out_dir.mkdir(parents=True, exist_ok=True)
    all_meta: dict[str, DatasetMetaEntry] = _load_existing_meta(out_dir)
    written = 0
    rebuilt = 0
    for meta_path in sorted(raw_dir.glob("*_meta.parquet")):
        name, entry = read_meta(meta_path)
        # _meta.json always covers every raw dataset; only the rebuild step
        # below is gated by --dataset / the change list.
        all_meta[name] = entry
        if only is not None and name != only:
            continue
        if changed is not None and name not in changed:
            continue
        raw_parquet = meta_path.with_name(f"{name}.parquet")
        shipped_parquet = out_dir / f"{name}.parquet"
        frame = pl.read_parquet(raw_parquet)
        embed_labels(frame, entry, shipped_parquet)
        entry["parquet_hash"] = _parquet_hash(shipped_parquet)
        written += 1
        rebuilt += 1
    if only is not None and written == 0:
        msg = (
            f"[{collection}] no dataset {only!r}; "
            f"available: {', '.join(sorted(all_meta))}"
        )
        raise SystemExit(msg)

    # _meta.json always comes from the full set, even for a single rebuild
    (out_dir / "_meta.json").write_text(
        json.dumps(all_meta, indent=1, ensure_ascii=False),
        encoding="utf-8",
        newline="\n",
    )
    _update_collection_sources(collection, data)
    n_undoc = sum(
        1
        for e in all_meta.values()
        for c in e["columns"].values()
        if c["label"] == "undocumented field"
    )
    print(
        f"[{collection}] {len(all_meta)} datasets packaged, "
        f"{rebuilt} rebuilt, {n_undoc} undocumented columns"
    )


def validate(collections: Iterable[str] = COLLECTIONS, raw: Path = RAW) -> None:
    """Check that every collection has matching raw data and metadata."""
    for collection in collections:
        raw_dir = raw / collection
        data_files = {
            p.stem for p in raw_dir.glob("*.parquet") if not p.stem.endswith("_meta")
        }
        meta_files = {
            p.stem.removesuffix("_meta") for p in raw_dir.glob("*_meta.parquet")
        }
        if not data_files:
            msg = (
                f"[{collection}] no raw datasets in {raw_dir}; "
                "run the exporters in data-raw/ first"
            )
            raise ValueError(msg)
        if data_files != meta_files:
            problems = []
            missing_meta = sorted(data_files - meta_files)
            missing_data = sorted(meta_files - data_files)
            if missing_meta:
                problems.append(f"data without metadata: {', '.join(missing_meta)}")
            if missing_data:
                problems.append(f"metadata without data: {', '.join(missing_data)}")
            raise ValueError(f"[{collection}] " + "; ".join(problems))
        for meta_path in sorted(raw_dir.glob("*_meta.parquet")):
            read_meta(meta_path)
    print("ok: raw inputs are valid")


def _parse_args(
    argv: Sequence[str] | None, collections: Iterable[str] = COLLECTIONS
) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="03_build_data.py",
        description="Package raw pharmadata files into the shipped parquet.",
    )
    parser.add_argument(
        "--collection",
        choices=collections,
        help="rebuild only this collection",
    )
    parser.add_argument(
        "--dataset",
        help="rebuild only this dataset (requires --collection)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the raw inputs without writing anything",
    )
    args = parser.parse_args(argv)
    if args.dataset and not args.collection:
        parser.error("--dataset requires --collection")
    return args


def _load_changed() -> dict[str, list[str]] | None:
    """The change list written by ``01b_detect_changes.py``, or None if absent."""
    path = PKG / "data-raw" / "_changed.json"
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def main(
    argv: Sequence[str] | None = None,
    collections: Iterable[str] = COLLECTIONS,
    raw: Path = RAW,
    data: Path = DATA,
    changed_map: dict[str, list[str]] | Literal["all"] | None = None,
) -> None:
    """Package every collection; ``--check`` validates the raw inputs only.

    *changed_map* overrides the change list: pass a mapping to force an
    incremental build, ``None`` to read ``data-raw/_changed.json`` (the
    default), or the string ``"all"`` to rebuild every dataset regardless.
    """
    args = _parse_args(argv, collections=collections)
    if changed_map is None:
        changes = _load_changed()
    elif changed_map == "all":
        changes = None
    else:
        changes = changed_map
    # --check always validates every collection; otherwise only collections
    # with changed raw data are validated (the rest have an empty raw/ dir).
    validate_collections = (
        list(collections)
        if args.check or changes is None
        else [c for c in collections if changes.get(c)]
    )
    if validate_collections:
        validate(collections=validate_collections, raw=raw)
    if args.check:
        return
    for collection in collections:
        if args.collection is None or collection == args.collection:
            changed = set(changes.get(collection, [])) if changes is not None else None
            build_collection(
                collection,
                only=args.dataset,
                raw=raw,
                data=data,
                changed=changed,
            )


if __name__ == "__main__":
    main()
