"""Generate each collection's ``__init__.py`` and ``.pyi`` stub from its data.

The sibling of ``data-raw/03_build_data.py`` on the code side: build_data ships
the parquet and ``_meta.json``, this writes the Python modules that expose them.
It iterates ``data.COLLECTIONS``, which is discovered by scanning ``_data``, so
a new dataset group needs no edit here - drop in ``_data/<name>/`` with a
``_collection.json``, run ``03_build_data``, then ``python data-raw/04_build_modules.py``
and its module and stub appear. Run from a checkout:

    uv run python data-raw/04_build_modules.py [--collection NAME]
"""

from __future__ import annotations

import argparse
from pathlib import Path
from string import Template
from typing import TYPE_CHECKING

from pharmadata._core import data

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

# The package source tree this writes into: src/pharmadata. Sibling of the
# data-raw/ scripts, two parents up then into src/pharmadata.
SRC = Path(__file__).resolve().parents[1] / "src" / "pharmadata"

# The line marking a file as machine-written, present in both faces.
GENERATED_BY = "Generated by data-raw/04_build_modules.py - do not edit."

# Shared body of a collection module: real defs, so great-docs reads them.
_MODULE_TEMPLATE = '''"""${kind} datasets from ${source}, lazily loaded as polars DataFrames.

Access a dataset as a module attribute, e.g. ``${name}.${example}``; its metadata
as ``${name}.${example}_meta`` or via ``meta(name)``.
"""

# ${generated_by}

from __future__ import annotations

from typing import TYPE_CHECKING

from pharmadata._core import collection, data
from pharmadata._core.meta import DatasetMeta, build

if TYPE_CHECKING:
    import pandas as pd
    import polars as pl
    import pyarrow as pa


def list_datasets() -> list[str]:
    """Names of the available ${kind} datasets, sorted alphabetically.

    Returns
    -------
    list[str]
        A list of dataset names.

    Examples
    --------
    >>> "${example}" in ${name}.list_datasets()
    True
    """
    return data.list_datasets("${name}")


def meta(name: str) -> DatasetMeta:
    """pyreadstat-style metadata of a dataset.

    Parameters
    ----------
    name : str
        The dataset name, e.g. ``"${example}"``.

    Returns
    -------
    DatasetMeta
        The metadata object the ``<name>_meta`` module attribute serves.

    Raises
    ------
    ValueError
        If *name* is not a known ${kind} dataset.

    Examples
    --------
    >>> ${name}.meta("${example}").column_names_to_labels["STUDYID"]
    'Study Identifier'
    """
    return build("${name}", name)


def meta_tables() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Dataset-level metadata: one row per dataset.

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per dataset, in the active output format, with the columns
        ``dataset, label, n_rows, n_cols``.

    Examples
    --------
    >>> ${name}.meta_tables().columns
    ['dataset', 'label', 'n_rows', 'n_cols']
    """
    return data.meta_tables("${name}")


def meta_columns() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Column-level metadata of every ${kind} dataset (long format).

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per column of every dataset, in the active output format,
        with the columns ``dataset, variable, label, type``.

    Examples
    --------
    >>> ${name}.meta_columns().columns
    ['dataset', 'variable', 'label', 'type']
    """
    return data.meta_columns("${name}")


def meta_specs() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Column-level specifications of every ${kind} dataset (long format).

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per variable, in the active output format, with the columns
        ``dataset, variable, label, type, mandatory, role``.

    Examples
    --------
    >>> ${name}.meta_specs().columns
    ['dataset', 'variable', 'label', 'type', 'mandatory', 'role']
    """
    return data.meta_specs("${name}")


def to_dict() -> dict[str, pa.Table | pl.DataFrame | pd.DataFrame]:
    """Every ${kind} dataset loaded at once, keyed by name.

    Reads the whole collection, so prefer the lazy attributes (e.g.
    ``${name}.${example}``) when only a few datasets are needed. Honors the active
    output format: with ``output_format="pandas"`` the values are pandas DataFrames.

    Returns
    -------
    dict[str, pa.Table | pl.DataFrame | pd.DataFrame]
        One entry per dataset, mapping each dataset name to its frame in the
        active output format.

    Examples
    --------
    >>> "${example}" in ${name}.to_dict()
    True
    """
    return collection.load_all("${name}")


collection.install(__name__, data.COLLECTIONS["${name}"])
'''


def module_source(spec: data.Collection) -> str:
    """The ``__init__.py`` text for one collection, from the shared template."""
    return Template(_MODULE_TEMPLATE).substitute(
        generated_by=GENERATED_BY,
        kind=spec.title.split(" (")[0],
        source=spec.source,
        name=spec.name,
        example=spec.example,
    )


def _stub_docstring(collection: str, name: str) -> str:
    """Markdown docstring for a dataset attribute: label, shape, and variables."""
    entry = data._meta_entry(collection, name)
    rows, cols = data.shape(collection, name)
    lines = [entry["label"] or name, "", f"{rows} rows x {cols} columns."]
    if entry["structure"]:
        lines.append(f"Structure: {entry['structure']}.")
    lines += ["", "Variables:", ""]
    lines += [
        f"- `{column}` ({info['type']}): {info['label'] or ''}".rstrip()
        for column, info in entry["columns"].items()
    ]
    return "\n".join(lines)


def _docstring_literal(text: str) -> str:
    """Wrap text as a stub docstring literal, escaping backslashes and quotes."""
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'"""{body}\n"""'


def _dataset_lines(collection: str, name: str) -> list[str]:
    """Stub lines for a dataset and its metadata, Final so assignment is a type error.

    The dataset attribute carries a generated docstring (label, shape, variables)
    so the static API reference documents it; the ``_meta`` partner stays bare.
    """
    return [
        f"{name}: Final[DataFrame]",
        _docstring_literal(_stub_docstring(collection, name)),
        f"{name}_meta: Final[DatasetMeta]",
    ]


def stub_source(collection: str, names: list[str]) -> str:
    """The ``.pyi`` stub text: the datasets as documented ``Final`` attributes."""
    stub = [
        f"# {GENERATED_BY}",
        "from typing import Final",
        "",
        "from pandas import DataFrame as PandasDataFrame",
        "from polars import DataFrame",
        "from pyarrow import Table",
        "",
        "from pharmadata import DatasetMeta",
        "",
        "def list_datasets() -> list[str]: ...",
        "def meta(name: str) -> DatasetMeta: ...",
        "def meta_tables() -> DataFrame | Table | PandasDataFrame: ...",
        "def meta_columns() -> DataFrame | Table | PandasDataFrame: ...",
        "def meta_specs() -> DataFrame | Table | PandasDataFrame: ...",
        "def to_dict() -> dict[str, DataFrame | Table | PandasDataFrame]: ...",
        "",
        "# Datasets are lazy attributes (module __getattr__); Final mirrors that",
        "# to a static checker.",
        *(line for name in names for line in _dataset_lines(collection, name)),
    ]
    return "\n".join(stub) + "\n"


def write_collection(spec: data.Collection, src: Path = SRC) -> list[Path]:
    """Write one collection's module and stub; return the paths written."""
    directory = src / spec.name
    directory.mkdir(parents=True, exist_ok=True)
    module = directory / "__init__.py"
    module.write_text(module_source(spec), encoding="utf-8", newline="\n")
    stub = directory / "__init__.pyi"
    stub.write_text(
        stub_source(spec.name, data.list_datasets(spec.name)),
        encoding="utf-8",
        newline="\n",
    )
    return [module, stub]


def generate(collections: Sequence[data.Collection], src: Path = SRC) -> list[Path]:
    """Write the module and stub of the given collections; return the paths."""
    return [path for spec in collections for path in write_collection(spec, src=src)]


def main(
    argv: Sequence[str] | None = None,
    collections: Iterable[data.Collection] = data.COLLECTIONS.values(),
    src: Path = SRC,
) -> None:
    """CLI entry: regenerate collection modules and stubs."""
    parser = argparse.ArgumentParser(
        prog="python data-raw/04_build_modules.py",
        description="Generate collection modules and stubs from the shipped data.",
    )
    by_name = {spec.name: spec for spec in collections}
    parser.add_argument(
        "--collection",
        choices=sorted(by_name),
        help="regenerate only this collection (default: every discovered one)",
    )
    args = parser.parse_args(argv)
    specs = (
        list(by_name.values())
        if args.collection is None
        else [by_name[args.collection]]
    )
    paths = generate(specs, src=src)
    print(f"generated {len(paths)} files for {len(specs)} collection(s)")


if __name__ == "__main__":
    main()
