"""ADaM datasets from the CDISC SDTM/ADaM Pilot Project, lazily loaded as polars DataFrames.

Access a dataset as a module attribute, e.g. ``cdiscpilotadam.adsl``; its metadata
as ``cdiscpilotadam.adsl_meta`` or via ``meta(name)``.
"""

# Generated by data-raw/04_build_modules.py - do not edit.

from __future__ import annotations

from typing import TYPE_CHECKING

from pharmadata._core import collection, data
from pharmadata._core.meta import DatasetMeta, build

if TYPE_CHECKING:
    import pandas as pd
    import polars as pl
    import pyarrow as pa


def list_datasets() -> list[str]:
    """Names of the available ADaM datasets, sorted alphabetically.

    Returns
    -------
    list[str]
        A list of dataset names.

    Examples
    --------
    >>> "adsl" in cdiscpilotadam.list_datasets()
    True
    """
    return data.list_datasets("cdiscpilotadam")


def meta(name: str) -> DatasetMeta:
    """pyreadstat-style metadata of a dataset.

    Parameters
    ----------
    name : str
        The dataset name, e.g. ``"adsl"``.

    Returns
    -------
    DatasetMeta
        The metadata object the ``<name>_meta`` module attribute serves.

    Raises
    ------
    ValueError
        If *name* is not a known ADaM dataset.

    Examples
    --------
    >>> cdiscpilotadam.meta("adsl").column_names_to_labels["STUDYID"]
    'Study Identifier'
    """
    return build("cdiscpilotadam", name)


def meta_tables() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Dataset-level metadata: one row per dataset.

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per dataset, in the active output format, with the columns
        ``dataset, label, n_rows, n_cols``.

    Examples
    --------
    >>> cdiscpilotadam.meta_tables().columns
    ['dataset', 'label', 'n_rows', 'n_cols']
    """
    return data.meta_tables("cdiscpilotadam")


def meta_columns() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Column-level metadata of every ADaM dataset (long format).

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per column of every dataset, in the active output format,
        with the columns ``dataset, variable, label, type``.

    Examples
    --------
    >>> cdiscpilotadam.meta_columns().columns
    ['dataset', 'variable', 'label', 'type']
    """
    return data.meta_columns("cdiscpilotadam")


def meta_specs() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Column-level specifications of every ADaM dataset (long format).

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per variable, in the active output format, with the columns
        ``dataset, variable, label, type, mandatory, role``.

    Examples
    --------
    >>> cdiscpilotadam.meta_specs().columns
    ['dataset', 'variable', 'label', 'type', 'mandatory', 'role']
    """
    return data.meta_specs("cdiscpilotadam")


def to_dict() -> dict[str, pa.Table | pl.DataFrame | pd.DataFrame]:
    """Every ADaM dataset loaded at once, keyed by name.

    Reads the whole collection, so prefer the lazy attributes (e.g.
    ``cdiscpilotadam.adsl``) when only a few datasets are needed. Honors the active
    output format: with ``output_format="pandas"`` the values are pandas DataFrames.

    Returns
    -------
    dict[str, pa.Table | pl.DataFrame | pd.DataFrame]
        One entry per dataset, mapping each dataset name to its frame in the
        active output format.

    Examples
    --------
    >>> "adsl" in cdiscpilotadam.to_dict()
    True
    """
    return collection.load_all("cdiscpilotadam")


collection.install(__name__, data.COLLECTIONS["cdiscpilotadam"])
