# Generated by data-raw/04_build_modules.py - do not edit.
from typing import Final

from pandas import DataFrame as PandasDataFrame
from polars import DataFrame
from pyarrow import Table

from pharmadata import DatasetMeta

def list_datasets() -> list[str]: ...
def meta(name: str) -> DatasetMeta: ...
def meta_tables() -> DataFrame | Table | PandasDataFrame: ...
def meta_columns() -> DataFrame | Table | PandasDataFrame: ...
def meta_specs() -> DataFrame | Table | PandasDataFrame: ...
def to_dict() -> dict[str, DataFrame | Table | PandasDataFrame]: ...

# Datasets are lazy attributes (module __getattr__); Final mirrors that
# to a static checker.
adadas: Final[DataFrame]
"""ADAS-Cog Analysis

12463 rows x 40 columns.
Structure: one record per subject per parameter per analysis visit per analysis date.

Variables:

- `STUDYID` (String): Study Identifier
- `SITEID` (String): Study Site Identifier
- `SITEGR1` (String): Pooled Site Group 1
- `USUBJID` (String): Unique Subject Identifier
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `ITTFL` (String): Intent-to-Treat Population Flag
- `EFFFL` (String): Efficacy Population Flag
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Date): Analysis Date
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `CHG` (Float64): Change from Baseline
- `PCHG` (Float64): Percent Change from Baseline
- `ABLFL` (String): Baseline Record Flag
- `ANL01FL` (String): Analysis Record Flag 01
- `DTYPE` (String): Derivation Type
- `AWRANGE` (String): Analysis Window Valid Relative Range
- `AWTARGET` (Float64): Analysis Window Target
- `AWTDIFF` (Float64): Analysis Window Diff from Target
- `AWLO` (Float64): Analysis Window Beginning Timepoint
- `AWHI` (Float64): Analysis Window Ending Timepoint
- `AWU` (String): Analysis Window Unit
- `QSSEQ` (Float64): Sequence Number
"""
adadas_meta: Final[DatasetMeta]
adae: Final[DataFrame]
"""Adverse Events Analysis Dataset

1191 rows x 55 columns.
Structure: one record per subject per adverse event.

Variables:

- `STUDYID` (String): Study Identifier
- `SITEID` (String): Study Site Identifier
- `USUBJID` (String): Unique Subject Identifier
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `SAFFL` (String): Safety Population Flag
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `ASTDT` (Date): Analysis Start Date
- `ASTDTF` (String): Analysis Start Date Imputation Flag
- `ASTDY` (Float64): Analysis Start Relative Day
- `AENDT` (Date): Analysis End Date
- `AENDY` (Float64): Analysis End Relative Day
- `ADURN` (Float64): AE Duration (N)
- `ADURU` (String): AE Duration Units
- `AETERM` (String): Reported Term for the Adverse Event
- `AELLT` (String): Lowest Level Term
- `AELLTCD` (Float64): Lowest Level Term Code
- `AEDECOD` (String): Dictionary-Derived Term
- `AEPTCD` (Float64): Preferred Term Code
- `AEHLT` (String): High Level Term
- `AEHLTCD` (Float64): High Level Term Code
- `AEHLGT` (String): High Level Group Term
- `AEHLGTCD` (Float64): High Level Group Term Code
- `AEBODSYS` (String): Body System or Organ Class
- `AESOC` (String): Primary System Organ Class
- `AESOCCD` (Float64): Primary System Organ Class Code
- `AESEV` (String): Severity/Intensity
- `AESER` (String): Serious Event
- `AESCAN` (String): Involves Cancer
- `AESCONG` (String): Congenital Anomaly or Birth Defect
- `AESDISAB` (String): Persist or Signif Disability/Incapacity
- `AESDTH` (String): Results in Death
- `AESHOSP` (String): Requires or Prolongs Hospitalization
- `AESLIFE` (String): Is Life Threatening
- `AESOD` (String): Occurred with Overdose
- `AEREL` (String): Causality
- `AEACN` (String): Action Taken with Study Treatment
- `AEOUT` (String): Outcome of Adverse Event
- `AESEQ` (Float64): Sequence Number
- `TRTEMFL` (String): Treatment Emergent Analysis Flag
- `AOCCFL` (String): 1st Occurrence of Any AE Flag
- `AOCCSFL` (String): 1st Occurrence of SOC Flag
- `AOCCPFL` (String): 1st Occurrence of Preferred Term Flag
- `AOCC02FL` (String): 1st Occurrence 02 Flag for Serious
- `AOCC03FL` (String): 1st Occurrence 03 Flag for Serious SOC
- `AOCC04FL` (String): 1st Occurrence 04 Flag for Serious PT
- `CQ01NAM` (String): Customized Query 01 Name
- `AOCC01FL` (String): 1st Occurrence 01 Flag for CQ01
"""
adae_meta: Final[DatasetMeta]
adcibc: Final[DataFrame]
"""CIBIC+ Analysis

730 rows x 36 columns.
Structure: one record per subject per parameter per analysis visit per analysis date.

Variables:

- `STUDYID` (String): Study Identifier
- `SITEID` (String): Study Site Identifier
- `SITEGR1` (String): Pooled Site Group 1
- `USUBJID` (String): Unique Subject Identifier
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `ITTFL` (String): Intent-to-Treat Population Flag
- `EFFFL` (String): Efficacy Population Flag
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Date): Analysis Date
- `PARAMCD` (String): Parameter Code
- `PARAM` (String): Parameter
- `PARAMN` (Float64): Parameter (N)
- `AVAL` (Float64): Analysis Value
- `ANL01FL` (String): Analysis Record Flag 01
- `DTYPE` (String): Derivation Type
- `AWRANGE` (String): Analysis Window Valid Relative Range
- `AWTARGET` (Float64): Analysis Window Target
- `AWTDIFF` (Float64): Analysis Window Diff from Target
- `AWLO` (Float64): Analysis Window Beginning Timepoint
- `AWHI` (Float64): Analysis Window Ending Timepoint
- `AWU` (String): Analysis Window Unit
- `QSSEQ` (Float64): Sequence Number
"""
adcibc_meta: Final[DatasetMeta]
adlbc: Final[DataFrame]
"""Analysis Dataset Lab Blood Chemistry

37132 rows x 46 columns.
Structure: one record per subject per parameter per analysis visit.

Variables:

- `STUDYID` (String): Study Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `USUBJID` (String): Unique Subject Identifier
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `TRTSDT` (Float64): Date of First Exposure to Treatment
- `TRTEDT` (Float64): Date of Last Exposure to Treatment
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `DSRAEFL` (String): Discontinued due to AE?
- `SAFFL` (String): Safety Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Float64): Analysis Date
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `PARCAT1` (String): Parameter Category 1
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `CHG` (Float64): Change from Baseline
- `A1LO` (Float64): Analysis Range 1 Lower Limit
- `A1HI` (Float64): Analysis Range 1 Upper Limit
- `R2A1LO` (Float64): Ratio to Analysis Range 1 Lower Limit
- `R2A1HI` (Float64): Ratio to Analysis Range 1 Upper Limit
- `BR2A1LO` (Float64): Base Ratio to Analysis Range 1 Lower Lim
- `BR2A1HI` (Float64): Base Ratio to Analysis Range 1 Upper Lim
- `ANL01FL` (String): Analysis Flag 01
- `ALBTRVAL` (Float64): Amount Threshold Range
- `ANRIND` (String): Analysis Reference Range Indicator
- `BNRIND` (String): Baseline Reference Range Indicator
- `ABLFL` (String): Baseline Record Flag
- `AENTMTFL` (String): Last value in treatment visit
- `LBSEQ` (Float64): Sequence Number
- `LBNRIND` (String): Reference Range Indicator
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
"""
adlbc_meta: Final[DatasetMeta]
adlbcpv: Final[DataFrame]
"""Analysis Dataset Lab Blood Chemistry (Previous Visit)

37132 rows x 46 columns.
Structure: one record per subject per parameter per analysis visit.

Variables:

- `STUDYID` (String): Study Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `USUBJID` (String): Unique Subject Identifier
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `TRTSDT` (Float64): Date of First Exposure to Treatment
- `TRTEDT` (Float64): Date of Last Exposure to Treatment
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `DSRAEFL` (String): Discontinued due to AE?
- `SAFFL` (String): Safety Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Float64): Analysis Date
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `PARCAT1` (String): Parameter Category 1
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `CHG` (Float64): Change from Baseline
- `A1LO` (Float64): Analysis Range 1 Lower Limit
- `A1HI` (Float64): Analysis Range 1 Upper Limit
- `R2A1LO` (Float64): Ratio to Analysis Range 1 Lower Limit
- `R2A1HI` (Float64): Ratio to Analysis Range 1 Upper Limit
- `BR2A1LO` (Float64): Base Ratio to Analysis Range 1 Lower Lim
- `BR2A1HI` (Float64): Base Ratio to Analysis Range 1 Upper Lim
- `ANL01FL` (String): Analysis Flag 01
- `ALBTRVAL` (Float64): Amount Threshold Range
- `ANRIND` (String): Analysis Reference Range Indicator
- `BNRIND` (String): Baseline Reference Range Indicator
- `ABLFL` (String): Baseline Record Flag
- `AENTMTFL` (String): Last value in treatment visit
- `LBSEQ` (Float64): Sequence Number
- `LBNRIND` (String): Reference Range Indicator
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
"""
adlbcpv_meta: Final[DatasetMeta]
adlbh: Final[DataFrame]
"""Analysis Dataset Lab Hematology

24966 rows x 46 columns.
Structure: one record per subject per parameter per analysis visit.

Variables:

- `STUDYID` (String): Study Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `USUBJID` (String): Unique Subject Identifier
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `TRTSDT` (Float64): Date of First Exposure to Treatment
- `TRTEDT` (Float64): Date of Last Exposure to Treatment
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `DSRAEFL` (String): Discontinued due to AE?
- `SAFFL` (String): Safety Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Float64): Analysis Date
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `PARCAT1` (String): Parameter Category 1
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `CHG` (Float64): Change from Baseline
- `A1LO` (Float64): Analysis Range 1 Lower Limit
- `A1HI` (Float64): Analysis Range 1 Upper Limit
- `R2A1LO` (Float64): Ratio to Analysis Range 1 Lower Limit
- `R2A1HI` (Float64): Ratio to Analysis Range 1 Upper Limit
- `BR2A1LO` (Float64): Base Ratio to Analysis Range 1 Lower Lim
- `BR2A1HI` (Float64): Base Ratio to Analysis Range 1 Upper Lim
- `ANL01FL` (String): Analysis Flag 01
- `ALBTRVAL` (Float64): Amount Threshold Range
- `ANRIND` (String): Analysis Reference Range Indicator
- `BNRIND` (String): Baseline Reference Range Indicator
- `ABLFL` (String): Baseline Record Flag
- `AENTMTFL` (String): Last value in treatment visit
- `LBSEQ` (Float64): Sequence Number
- `LBNRIND` (String): Reference Range Indicator
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
"""
adlbh_meta: Final[DatasetMeta]
adlbhpv: Final[DataFrame]
"""Analysis Dataset Lab Hematology (Previous Visit)

24966 rows x 46 columns.
Structure: one record per subject per parameter per analysis visit.

Variables:

- `STUDYID` (String): Study Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `USUBJID` (String): Unique Subject Identifier
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `TRTSDT` (Float64): Date of First Exposure to Treatment
- `TRTEDT` (Float64): Date of Last Exposure to Treatment
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `DSRAEFL` (String): Discontinued due to AE?
- `SAFFL` (String): Safety Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Float64): Analysis Date
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `PARCAT1` (String): Parameter Category 1
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `CHG` (Float64): Change from Baseline
- `A1LO` (Float64): Analysis Range 1 Lower Limit
- `A1HI` (Float64): Analysis Range 1 Upper Limit
- `R2A1LO` (Float64): Ratio to Analysis Range 1 Lower Limit
- `R2A1HI` (Float64): Ratio to Analysis Range 1 Upper Limit
- `BR2A1LO` (Float64): Base Ratio to Analysis Range 1 Lower Lim
- `BR2A1HI` (Float64): Base Ratio to Analysis Range 1 Upper Lim
- `ANL01FL` (String): Analysis Flag 01
- `ALBTRVAL` (Float64): Amount Threshold Range
- `ANRIND` (String): Analysis Reference Range Indicator
- `BNRIND` (String): Baseline Reference Range Indicator
- `ABLFL` (String): Baseline Record Flag
- `AENTMTFL` (String): Last value in treatment visit
- `LBSEQ` (Float64): Sequence Number
- `LBNRIND` (String): Reference Range Indicator
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
"""
adlbhpv_meta: Final[DatasetMeta]
adlbhy: Final[DataFrame]
"""Analysis Dataset Lab Hy's Law

9954 rows x 43 columns.
Structure: one record per subject per parameter per analysis visit.

Variables:

- `STUDYID` (String): Study Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `USUBJID` (String): Unique Subject Identifier
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `DSRAEFL` (String): Discontinued due to AE?
- `SAFFL` (String): Safety Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Date): Analysis Date
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `PARAMTYP` (String): Parameter Type
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `PARCAT1` (String): Parameter Category 1
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `A1LO` (Float64): Analysis Range 1 Lower Limit
- `A1HI` (Float64): Analysis Range 1 Upper Limit
- `R2A1LO` (Float64): Ratio to Analysis Range 1 Lower Limit
- `R2A1HI` (Float64): Ratio to Analysis Range 1 Upper Limit
- `BR2A1LO` (Float64): Base Ratio to Analysis Range 1 Lower Lim
- `BR2A1HI` (Float64): Base Ratio to Analysis Range 1 Upper Lim
- `ABLFL` (String): Baseline Record Flag
- `SHIFT1` (String): Shift 1
- `SHIFT1N` (Float64): Shift 1 (N)
- `CRIT1` (String): Analysis Criterion 1
- `CRIT1FL` (String): Criterion 1 Evaluation Result Flag
- `CRIT1FN` (Float64): Criterion 1 Evaluation Result Flag (N)
"""
adlbhy_meta: Final[DatasetMeta]
adnpix: Final[DataFrame]
"""NPI-X Item Analysis Data

31140 rows x 41 columns.
Structure: one record per subject per parameter per analysis visit per analysis date.

Variables:

- `STUDYID` (String): Study Identifier
- `SITEID` (String): Study Site Identifier
- `SITEGR1` (String): Pooled Site Group 1
- `USUBJID` (String): Unique Subject Identifier
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `ITTFL` (String): Intent-to-Treat Population Flag
- `EFFFL` (String): Efficacy Population Flag
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `ADY` (Float64): Analysis Relative Day
- `ADT` (Date): Analysis Date
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `PARAMN` (Float64): Parameter (N)
- `PARAMTYP` (String): Parameter Type
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `CHG` (Float64): Change from Baseline
- `PCHG` (Float64): Percent Change from Baseline
- `ABLFL` (String): Baseline Record Flag
- `ANL01FL` (String): Analysis Flag 01
- `DTYPE` (String): Derivation Type
- `AWRANGE` (String): Analysis Window Valid Relative Range
- `AWTARGET` (Float64): Analysis Window Target
- `AWTDIFF` (Float64): Analysis Window Diff from Target
- `AWLO` (Float64): Analysis Window Beginning Timepoint
- `AWHI` (Float64): Analysis Window Ending Timepoint
- `AWU` (String): Analysis Window Unit
- `QSSEQ` (Float64): Sequence Number
"""
adnpix_meta: Final[DatasetMeta]
adsl: Final[DataFrame]
"""Subject-Level Analysis

254 rows x 49 columns.
Structure: one record per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `SITEID` (String): Study Site Identifier
- `SITEGR1` (String): Pooled Site Group 1
- `ARM` (String): Description of Planned Arm
- `TRT01P` (String): Planned Treatment for Period 01
- `TRT01PN` (Float64): Planned Treatment for Period 01 (N)
- `TRT01A` (String): Actual Treatment for Period 01
- `TRT01AN` (Float64): Actual Treatment for Period 01 (N)
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `TRTDURD` (Float64): Total Treatment Duration (Days)
- `AVGDD` (Float64): Avg Daily Dose (as planned)
- `CUMDOSE` (Float64): Cumulative Dose (as planned)
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `AGEU` (String): Age Units
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `ETHNIC` (String): Ethnicity
- `SAFFL` (String): Safety Population Flag
- `ITTFL` (String): Intent-To-Treat Population Flag
- `EFFFL` (String): Efficacy Population Flag
- `COMP8FL` (String): Completers of Week 8 Population Flag
- `COMP16FL` (String): Completers of Week 16 Population Flag
- `COMP24FL` (String): Completers of Week 24 Population Flag
- `DISCONFL` (String): Did the Subject Discontinue the Study?
- `DSRAEFL` (String): Discontinued due to AE?
- `DTHFL` (String): Subject Died?
- `BMIBL` (Float64): Baseline BMI (kg/m^2)
- `BMIBLGR1` (String): Pooled Baseline BMI Group 1
- `HEIGHTBL` (Float64): Baseline Height (cm)
- `WEIGHTBL` (Float64): Baseline Weight (kg)
- `EDUCLVL` (Float64): Years of Education
- `DISONSDT` (Date): Date of Onset of Disease
- `DURDIS` (Float64): Duration of Disease (Months)
- `DURDSGR1` (String): Pooled Disease Duration Group 1
- `VISIT1DT` (Date): Date of Visit 1
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `VISNUMEN` (Float64): End of Trt Visit (Vis 12 or Early Term.)
- `RFENDT` (Date): Date of Discontinuation/Completion
- `DCDECOD` (String): Standardized Disposition Term
- `EOSSTT` (String): End of Study Status
- `DCSREAS` (String): Reason for Discontinuation from Study
- `MMSETOT` (Float64): MMSE Total
"""
adsl_meta: Final[DatasetMeta]
adtte: Final[DataFrame]
"""AE Time To 1st Derm. Event Analysis

254 rows x 26 columns.
Structure: one record per subject per parameter.

Variables:

- `STUDYID` (String): Study Identifier
- `SITEID` (String): Study Site Identifier
- `USUBJID` (String): Unique Subject Identifier
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `TRTDUR` (Float64): Duration of treatment (days)
- `TRTP` (String): Planned Treatment
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `PARAM` (String): Parameter
- `PARAMCD` (String): Parameter Code
- `AVAL` (Float64): Analysis Value
- `STARTDT` (Date): Time to Event Origin Date for Subject
- `ADT` (Date): Analysis Date
- `CNSR` (Float64): Censor
- `EVNTDESC` (String): Event or Censoring Description
- `SRCDOM` (String): Source Domain
- `SRCVAR` (String): Source Variable
- `SRCSEQ` (Float64): Source Sequence Number
- `SAFFL` (String): Safety Population Flag
"""
adtte_meta: Final[DatasetMeta]
advs: Final[DataFrame]
"""Vital Signs Analysis Dataset

32139 rows x 35 columns.
Structure: one record per subject per parameter per analysis visit per analysis timepoint.

Variables:

- `STUDYID` (String): Study Identifier
- `SITEID` (String): Study Site Identifier
- `USUBJID` (String): Unique Subject Identifier
- `AGE` (Float64): Age
- `AGEGR1` (String): Pooled Age Group 1
- `AGEGR1N` (Float64): Pooled Age Group 1 (N)
- `RACE` (String): Race
- `RACEN` (Float64): Race (N)
- `SEX` (String): Sex
- `SAFFL` (String): Safety Population Flag
- `TRTSDT` (Date): Date of First Exposure to Treatment
- `TRTEDT` (Date): Date of Last Exposure to Treatment
- `TRTP` (String): Planned Treatment
- `TRTPN` (Float64): Planned Treatment (N)
- `TRTA` (String): Actual Treatment
- `TRTAN` (Float64): Actual Treatment (N)
- `PARAMCD` (String): Parameter Code
- `PARAM` (String): Parameter
- `PARAMN` (Float64): Parameter (N)
- `ADT` (Date): Analysis Date
- `ADY` (Float64): Analysis Relative Day
- `ATPTN` (Float64): Analysis Timepoint (N)
- `ATPT` (String): Analysis Timepoint
- `AVISIT` (String): Analysis Visit
- `AVISITN` (Float64): Analysis Visit (N)
- `AVAL` (Float64): Analysis Value
- `BASE` (Float64): Baseline Value
- `BASETYPE` (String): Baseline Type
- `CHG` (Float64): Change from Baseline
- `PCHG` (Float64): Percent Change from Baseline
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VSSEQ` (Float64): Sequence Number
- `ANL01FL` (String): Analysis Flag 01
- `ABLFL` (String): Baseline Record Flag
"""
advs_meta: Final[DatasetMeta]
