# Generated by data-raw/04_build_modules.py - do not edit.
from typing import Final

from pandas import DataFrame as PandasDataFrame
from polars import DataFrame
from pyarrow import Table

from pharmadata import DatasetMeta

def list_datasets() -> list[str]: ...
def meta(name: str) -> DatasetMeta: ...
def meta_tables() -> DataFrame | Table | PandasDataFrame: ...
def meta_columns() -> DataFrame | Table | PandasDataFrame: ...
def meta_specs() -> DataFrame | Table | PandasDataFrame: ...
def to_dict() -> dict[str, DataFrame | Table | PandasDataFrame]: ...

# Datasets are lazy attributes (module __getattr__); Final mirrors that
# to a static checker.
ae: Final[DataFrame]
"""Adverse Events

1191 rows x 35 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `AESEQ` (Float64): Sequence Number
- `AESPID` (String): Sponsor-Defined Identifier
- `AETERM` (String): Reported Term for the Adverse Event
- `AELLT` (String): Lowest Level Term
- `AELLTCD` (Float64): Lowest Level Term Code
- `AEDECOD` (String): Dictionary-Derived Term
- `AEPTCD` (Float64): Preferred Term Code
- `AEHLT` (String): High Level Term
- `AEHLTCD` (Float64): High Level Term Code
- `AEHLGT` (String): High Level Group Term
- `AEHLGTCD` (Float64): High Level Group Term Code
- `AEBODSYS` (String): Body System or Organ Class
- `AEBDSYCD` (Float64): Body System or Organ Class Code
- `AESOC` (String): Primary System Organ Class
- `AESOCCD` (Float64): Primary System Organ Class Code
- `AESEV` (String): Severity/Intensity
- `AESER` (String): Serious Event
- `AEACN` (String): Action Taken with Study Treatment
- `AEREL` (String): Causality
- `AEOUT` (String): Outcome of Adverse Event
- `AESCAN` (String): Involves Cancer
- `AESCONG` (String): Congenital Anomaly or Birth Defect
- `AESDISAB` (String): Persist or Signif Disability/Incapacity
- `AESDTH` (String): Results in Death
- `AESHOSP` (String): Requires or Prolongs Hospitalization
- `AESLIFE` (String): Is Life Threatening
- `AESOD` (String): Occurred with Overdose
- `AEDTC` (String): Date/Time of Collection
- `AESTDTC` (String): Start Date/Time of Adverse Event
- `AEENDTC` (String): End Date/Time of Adverse Event
- `AESTDY` (Float64): Study Day of Start of Adverse Event
- `AEENDY` (Float64): Study Day of End of Adverse Event
"""
ae_meta: Final[DatasetMeta]
ae_ophtha: Final[DataFrame]
"""Adverse Events for Ophthalmology

1191 rows x 37 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `AESEQ` (Float64): Sequence Number
- `AESPID` (String): Sponsor-Defined Identifier
- `AETERM` (String): Reported Term for the Adverse Event
- `AELLT` (String): Lowest Level Term
- `AELLTCD` (Float64): Lowest Level Term Code
- `AEDECOD` (String): Dictionary-Derived Term
- `AEPTCD` (Float64): Preferred Term Code
- `AEHLT` (String): High Level Term
- `AEHLTCD` (Float64): High Level Term Code
- `AEHLGT` (String): High Level Group Term
- `AEHLGTCD` (Float64): High Level Group Term Code
- `AEBODSYS` (String): Body System or Organ Class
- `AEBDSYCD` (Float64): Body System or Organ Class Code
- `AESOC` (String): Primary System Organ Class
- `AESOCCD` (Float64): Primary System Organ Class Code
- `AESEV` (String): Severity/Intensity
- `AESER` (String): Serious Event
- `AEACN` (String): Action Taken with Study Treatment
- `AEREL` (String): Causality
- `AEOUT` (String): Outcome of Adverse Event
- `AESCAN` (String): Involves Cancer
- `AESCONG` (String): Congenital Anomaly or Birth Defect
- `AESDISAB` (String): Persist or Signif Disability/Incapacity
- `AESDTH` (String): Results in Death
- `AESHOSP` (String): Requires or Prolongs Hospitalization
- `AESLIFE` (String): Is Life Threatening
- `AESOD` (String): Occurred with Overdose
- `AEDTC` (String): Date/Time of Collection
- `AESTDTC` (String): Start Date/Time of Adverse Event
- `AEENDTC` (String): End Date/Time of Adverse Event
- `AESTDY` (Float64): Study Day of Start of Adverse Event
- `AEENDY` (Float64): Study Day of End of Adverse Event
- `AELAT` (String): Laterality
- `AELOC` (String): Location
"""
ae_ophtha_meta: Final[DatasetMeta]
ag_neuro: Final[DataFrame]
"""Procedure Agents Dataset-neuro

68 rows x 13 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `AGSEQ` (Int32): Sequence Number
- `AGTRT` (String): Reported Agent Name
- `AGCAT` (String): Category for Agent
- `AGDOSE` (String): Dose per Administration
- `AGDOSEU` (String): Dose Units
- `AGROUTE` (String): Route of Administration
- `AGLNKID` (Float64): Link ID
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `AGSTDTC` (String): Start Date/Time of Agent
"""
ag_neuro_meta: Final[DatasetMeta]
be: Final[DataFrame]
"""Biospecimen Events

43 rows x 13 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `BESEQ` (Float64): Sequence Number
- `BEREFID` (String): Reference ID
- `BELNKID` (Boolean): Link Identifier
- `BETERM` (String): Reported Term for the Biospecimen Event
- `BECAT` (String): Category for Biospecimen Event
- `BELOC` (String): Anatomical Location of Event
- `VISITNUM` (Float64): Visit Number
- `BEDTC` (String): Date/Time of Specimen Collection
- `BESTDTC` (String): Start Date/Time of Biospecimen Event
- `BEENDTC` (String): End Date/Time of Biospecimen Event
"""
be_meta: Final[DatasetMeta]
ce_vaccine: Final[DataFrame]
"""Clinical Events for Vaccine

44 rows x 29 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `CESEQ` (Float64): Sequence Number
- `CELNKID` (String): Link ID
- `CELNKGRP` (String): Link Group ID
- `CETERM` (String): Reported Term for the Clinical Event
- `CEDECOD` (String): Dictionary-Derived Term
- `CELAT` (String): Laterality of Location of Clinical Event
- `CELOC` (String): Location of Clinical Event
- `CECAT` (String): Category for Clinical Event
- `CESCAT` (String): Subcategory for Clinical Event
- `CEPRESP` (String): Clinical Event Pre-Specified
- `CEOCCUR` (String): Clinical Event Occurrence
- `CESEV` (String): Severity/Intensity
- `CEREL` (String): Causality
- `CEOUT` (String): Outcome of Clinical Event
- `EPOCH` (String): Epoch
- `CEDTC` (String): Date/Time of Event Collection
- `CESTDTC` (String): Start Date/Time of Clinical Event
- `CEENDTC` (String): End Date/Time of Clinical Event
- `CEDUR` (String): Duration of Clinical Event
- `CETPT` (String): Planned Time Point Name
- `CETPTNUM` (Float64): Planned Time Point Number
- `CETPTREF` (String): Time Point Reference
- `CERFTDTC` (String): Date/Time of Reference Time Point
- `CEEVINTX` (String): Evaluation Interval Text
- `CESTAT` (String): Completion Status
- `CEREASND` (String): Reason Clinical Event Not Collected
"""
ce_vaccine_meta: Final[DatasetMeta]
cm: Final[DataFrame]
"""Concomitant Medication

7510 rows x 22 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `CMSEQ` (Float64): Sequence Number
- `CMSPID` (String): Sponsor-Defined Identifier
- `CMTRT` (String): Reported Name of Drug, Med, or Therapy
- `CMDECOD` (String): Standardized Medication Name
- `CMINDC` (String): Indication
- `CMCLAS` (String): Medication Class
- `CMDOSE` (Float64): Dose per Administration
- `CMDOSU` (String): Dose Units
- `CMDOSFRQ` (String): Dosing Frequency per Interval
- `CMROUTE` (String): Route of Administration
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `CMDTC` (String): Date/Time of Collection
- `CMSTDTC` (String): Start Date/Time of Medication
- `CMENDTC` (String): End Date/Time of Medication
- `CMSTDY` (Float64): Study Day of Start of Medication
- `CMENDY` (Float64): Study Day of End of Medication
- `CMENRTPT` (String): End Relative to Reference Time Point
"""
cm_meta: Final[DatasetMeta]
dm: Final[DataFrame]
"""Demography

306 rows x 28 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `RFXSTDTC` (String): Date/Time of First Study Treatment
- `RFXENDTC` (String): Date/Time of Last Study Treatment
- `RFICDTC` (String): Date/Time of Informed Consent
- `RFPENDTC` (String): Date/Time of End of Participation
- `DTHDTC` (String): Date/Time of Death
- `DTHFL` (String): Subject Death Flag
- `SITEID` (String): Study Site Identifier
- `BRTHDTC` (String): Date/Time of Birth
- `AGE` (Float64): Age
- `AGEU` (String): Age Units
- `SEX` (String): Sex
- `RACE` (String): Race
- `ETHNIC` (String): Ethnicity
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `ACTARMCD` (String): Actual Arm Code
- `ACTARM` (String): Description of Actual Arm
- `COUNTRY` (String): Country
- `DMDTC` (String): Date/Time of Collection
- `DMDY` (Float64): Study Day of Collection
- `ARMNRS` (String): Reason Arm and/or Actual Arm is Null
- `ACTARMUD` (String): Description of Unplanned Actual Arm
"""
dm_meta: Final[DatasetMeta]
dm_metabolic: Final[DataFrame]
"""Demographic Dataset-metabolic

5 rows x 28 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `RFXSTDTC` (String): Date/Time of First Study Treatment
- `RFXENDTC` (String): Date/Time of Last Study Treatment
- `RFICDTC` (String): Date/Time of Informed Consent
- `RFPENDTC` (String): Date/Time of End of Participation
- `DTHDTC` (String): Date/Time of Death
- `DTHFL` (String): Subject Death Flag
- `SITEID` (String): Study Site Identifier
- `BRTHDTC` (String): Date/Time of Birth
- `AGE` (Float64): Age
- `AGEU` (String): Age Units
- `SEX` (String): Sex
- `RACE` (String): Race
- `ETHNIC` (String): Ethnicity
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `ACTARMCD` (String): Actual Arm Code
- `ACTARM` (String): Description of Actual Arm
- `COUNTRY` (String): Country
- `DMDTC` (String): Date/Time of Collection
- `DMDY` (Float64): Study Day of Collection
- `ARMNRS` (String): Reason Arm and/or Actual Arm is Null
- `ACTARMUD` (String): Description of Unplanned Actual Arm
"""
dm_metabolic_meta: Final[DatasetMeta]
dm_neuro: Final[DataFrame]
"""Demographic Dataset-neuro

15 rows x 28 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `RFXSTDTC` (String): Date/Time of First Study Treatment
- `RFXENDTC` (String): Date/Time of Last Study Treatment
- `RFICDTC` (String): Date/Time of Informed Consent
- `RFPENDTC` (String): Date/Time of End of Participation
- `DTHDTC` (String): Date/Time of Death
- `DTHFL` (String): Subject Death Flag
- `SITEID` (String): Study Site Identifier
- `BRTHDTC` (String): Date/Time of Birth
- `AGE` (Float64): Age
- `AGEU` (String): Age Units
- `SEX` (String): Sex
- `RACE` (String): Race
- `ETHNIC` (String): Ethnicity
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `ACTARMCD` (String): Actual Arm Code
- `ACTARM` (String): Description of Actual Arm
- `COUNTRY` (String): Country
- `DMDTC` (String): Date/Time of Collection
- `DMDY` (Float64): Study Day of Collection
- `ARMNRS` (String): Reason Arm and/or Actual Arm is Null
- `ACTARMUD` (String): Description of Unplanned Actual Arm
"""
dm_neuro_meta: Final[DatasetMeta]
dm_peds: Final[DataFrame]
"""Demographic Dataset-pediatrics

5 rows x 28 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `RFXSTDTC` (String): Date/Time of First Study Treatment
- `RFXENDTC` (String): Date/Time of Last Study Treatment
- `RFICDTC` (String): Date/Time of Informed Consent
- `RFPENDTC` (String): Date/Time of End of Participation
- `DTHDTC` (String): Date/Time of Death
- `DTHFL` (String): Subject Death Flag
- `SITEID` (String): Study Site Identifier
- `BRTHDTC` (String): Date/Time of Birth
- `AGE` (Float64): Age
- `AGEU` (String): Age Units
- `SEX` (String): Sex
- `RACE` (String): Race
- `ETHNIC` (String): Ethnicity
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `ACTARMCD` (String): Actual Arm Code
- `ACTARM` (String): Description of Actual Arm
- `COUNTRY` (String): Country
- `DMDTC` (String): Date/Time of Collection
- `DMDY` (Float64): Study Day of Collection
- `ARMNRS` (String): Reason Arm and/or Actual Arm is Null
- `ACTARMUD` (String): Description of Unplanned Actual Arm
"""
dm_peds_meta: Final[DatasetMeta]
dm_vaccine: Final[DataFrame]
"""Demographics for Vaccine

2 rows x 30 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `RFXSTDTC` (String): Date/Time of First Study Treatment
- `RFXENDTC` (String): Date/Time of Last Study Treatment
- `RFICDTC` (String): Date/Time of Informed Consent
- `RFPENDTC` (String): Date/Time of End of Participation
- `DTHDTC` (String): Date/Time of Death
- `DTHFL` (String): Subject Death Flag
- `SITEID` (Float64): Study Site Identifier
- `INVID` (Float64): Investigator Identifier
- `INVNAM` (String): Investigator Name
- `BRTHDTC` (String): Date/Time of Birth
- `AGE` (Float64): Age
- `AGEU` (String): Age Units
- `SEX` (String): Sex
- `RACE` (String): Race
- `ETHNIC` (String): Ethnicity
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `ACTARMCD` (String): Actual Arm Code
- `ACTARM` (String): Description of Actual Arm
- `COUNTRY` (String): Country
- `DMDTC` (String): Date/Time of Collection
- `DMDY` (Int32): Study Day of Collection
- `ARMNRS` (String): Reason Arm and/or Actual Arm is Null
- `ACTARMUD` (String): Description of Unplanned Actual Arm
"""
dm_vaccine_meta: Final[DatasetMeta]
ds: Final[DataFrame]
"""Disposition

850 rows x 13 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `DSSEQ` (Int32): Sequence Number
- `DSSPID` (String): Sponsor-Defined Identifier
- `DSTERM` (String): Reported Term for the Disposition Event
- `DSDECOD` (String): Standardized Disposition Term
- `DSCAT` (String): Category for Disposition Event
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `DSDTC` (String): Date/Time of Collection
- `DSSTDTC` (String): Start Date/Time of Disposition Event
- `DSSTDY` (Float64): Study Day of Start of Disposition Event
"""
ds_meta: Final[DatasetMeta]
eg: Final[DataFrame]
"""Electrocardiogram

26717 rows x 23 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `EGSEQ` (Float64): Sequence Number
- `EGTESTCD` (String): ECG Test Short Name
- `EGTEST` (String): ECG Test Name
- `EGORRES` (String): Result or Finding in Original Units
- `EGORRESU` (String): Original Units
- `EGSTRESC` (String): Character Result/Finding in Std Format
- `EGSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `EGSTRESU` (String): Standard Units
- `EGSTAT` (String): Completion Status
- `EGLOC` (String): Location of Vital Signs Measurement
- `EGBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EGDTC` (String): Date/Time of Measurements
- `EGDY` (Float64): Study Day of Vital Signs
- `EGTPT` (String): Planned Time Point Number
- `EGTPTNUM` (Float64): Time Point Number
- `EGELTM` (String): Planned Elapsed Time from Time Point Ref
- `EGTPTREF` (String): Time Point Reference
"""
eg_meta: Final[DatasetMeta]
ex: Final[DataFrame]
"""Exposure

591 rows x 17 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `EXSEQ` (Float64): Sequence Number
- `EXTRT` (String): Name of Actual Treatment
- `EXDOSE` (Float64): Dose per Administration
- `EXDOSU` (String): Dose Units
- `EXDOSFRM` (String): Dose Form
- `EXDOSFRQ` (String): Dosing Frequency per Interval
- `EXROUTE` (String): Route of Administration
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EXSTDTC` (String): Start Date/Time of Treatment
- `EXENDTC` (String): End Date/Time of Treatment
- `EXSTDY` (Float64): Study Day of Start of Treatment
- `EXENDY` (Float64): Study Day of End of Treatment
"""
ex_meta: Final[DatasetMeta]
ex_ophtha: Final[DataFrame]
"""Exposure for Ophthalmology

591 rows x 19 columns.

Variables:

- `USUBJID` (String): Unique Subject Identifier
- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `EXSEQ` (Float64): Sequence Number
- `EXTRT` (String): Name of Actual Treatment
- `EXDOSE` (Float64): Dose per Administration
- `EXDOSU` (String): Dose Units
- `EXDOSFRM` (String): Dose Form
- `EXDOSFRQ` (String): Dose Frequency per Interval
- `EXROUTE` (String): Route of Administration
- `EXLOC` (String): Location of Dose Administration
- `EXLAT` (String): Laterality
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EXSTDTC` (String): Start Date/Time of Treatment
- `EXENDTC` (String): End Date/Time of Treatment
- `EXSTDY` (Float64): Study Day of Start of Treatment
- `EXENDY` (Float64): Study Day of End of Treatment
"""
ex_ophtha_meta: Final[DatasetMeta]
ex_vaccine: Final[DataFrame]
"""Exposures for Vaccine

4 rows x 19 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `EXSEQ` (Float64): Sequence Number
- `EXLNKGRP` (String): Link Group ID
- `EXLNKID` (String): Link ID
- `EXTRT` (String): Name of Actual Treatment
- `EXCAT` (String): Category of Treatment
- `EXDOSE` (Float64): Dose per Administration
- `EXDOSU` (String): Dose Units
- `EXDOSFRM` (String): Dose Form
- `EXROUTE` (String): Route of Administration
- `EXLOC` (String): Location of Dose Administration
- `EXLAT` (String): Laterality
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `EPOCH` (String): Epoch
- `EXSTDTC` (String): Start Date/Time of Treatment
- `EXENDTC` (String): End Date/Time of Treatment
"""
ex_vaccine_meta: Final[DatasetMeta]
face_vaccine: Final[DataFrame]
"""Findings About Clinical Events for Vaccine

307 rows x 30 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `FASEQ` (Int32): Sequence Number
- `FALNKGRP` (String): Link Group ID
- `FALAT` (String): Laterality
- `FALNKID` (String): Link ID
- `FALOC` (String): Location of the Finding About
- `FATESTCD` (String): Findings About Test Short Name
- `FATEST` (String): Findings About Test Name
- `FAOBJ` (String): Object of the Observation
- `FACAT` (String): Category for Findings About
- `FASCAT` (String): Subcategory for Findings About
- `FAEVAL` (String): Evaluator
- `FAORRES` (String): Result or Finding in Original Units
- `FAORRESU` (String): Original Units
- `EPOCH` (String): Epoch
- `FADTC` (String): Date/Time of Collection
- `FADY` (Float64): Study Day of Collection
- `FATPT` (String): Planned Time Point Name
- `FATPTNUM` (Float64): Planned Time Point Number
- `FATPTREF` (String): Time Point Reference
- `FARFTDTC` (String): Date/Time of Reference Time Point
- `FAEVLINT` (String): Evaluation Interval
- `FAEVINTX` (String): Evaluation Interval Text
- `FASTAT` (String): Completion Status
- `FAREASND` (String): Reason Not Performed
- `FASTRESC` (String): Character Result/Finding in Std Format
- `FASTRESN` (Float64): Numeric Result/Finding in Standard Units
- `FASTRESU` (String): Standard Units
"""
face_vaccine_meta: Final[DatasetMeta]
is_ada: Final[DataFrame]
"""Immunogenicity Specimen Assessments for ADA

691 rows x 27 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `ISSEQ` (Int32): Sequence Number
- `ISTESTCD` (String): Immunogenicity Test/Exam Short Name
- `ISTEST` (String): Immunogenicity Test or Examination Name
- `ISBDAGNT` (String): Binding Agent
- `ISCAT` (String): Category for Immunogenicity Test
- `ISORRES` (String): Results or Findings in Original Units
- `ISORRESU` (String): Original Units
- `ISSTRESC` (String): Character Result/Finding in Std Format
- `ISSTRESN` (Float64): Numeric Results/Findings in Std. Units
- `ISSTRESU` (String): Standard Units
- `ISSTAT` (String): Completion Status
- `ISREASND` (String): Reason Not Done
- `ISNAM` (String): Vendor Name
- `ISSPEC` (String): Specimen Type
- `ISBLFL` (String): Baseline Flag
- `ISLLOQ` (String): Lower Limit of Quantitation
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `ISDTC` (String): Date/Time of Collection
- `ISDY` (Float64): Study Day of Visit/Collection/Exam
- `ISTPT` (String): Planned Time Point Name
- `ISTPTNUM` (Float64): Planned Time Point Number
"""
is_ada_meta: Final[DatasetMeta]
is_vaccine: Final[DataFrame]
"""Immunogenicity Specimen Assessments for Vaccine

16 rows x 24 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `ISSEQ` (Int32): Sequence Number
- `ISTESTCD` (String): Immunogenicity Test/Exam Short Name
- `ISTEST` (String): Immunogenicity Test or Exam Name
- `ISCAT` (String): Category for Immunogenicity Test
- `ISORRES` (String): Result or Finding in Original Units
- `ISORRESU` (String): Original Units
- `ISSTRESC` (String): Character Result/Finding in Std Format
- `ISSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `ISSTRESU` (String): Standard Units
- `ISSTAT` (String): Completion Status
- `ISREASND` (String): Reason Not Done
- `ISNAM` (String): Vendor Name
- `ISSPEC` (String): Specimen Type
- `ISMETHOD` (String): Method of Test or Examination
- `ISBLFL` (String): Baseline Flag
- `ISLLOQ` (Float64): Lower Limit of Quantitation
- `VISITNUM` (Float64): Visit Number
- `EPOCH` (String): Epoch
- `ISDTC` (String): Date/Time of Collection
- `ISDY` (String): Study Day of Collection
- `ISULOQ` (Float64): Upper Limit of Quantitation
"""
is_vaccine_meta: Final[DatasetMeta]
lb: Final[DataFrame]
"""Laboratory Measurements

59580 rows x 23 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Float64): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBORNRLO` (String): Reference Range Lower Limit in Orig Unit
- `LBORNRHI` (String): Reference Range Upper Limit in Orig Unit
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBSTNRLO` (Float64): Reference Range Lower Limit-Std Units
- `LBSTNRHI` (Float64): Reference Range Upper Limit-Std Units
- `LBNRIND` (String): Reference Range Indicator
- `LBBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lb_meta: Final[DatasetMeta]
lb_metabolic: Final[DataFrame]
"""Laboratory Measurements Dataset-metabolic

309 rows x 24 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Int32): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBORNRLO` (String): Reference Range Lower Limit in Orig Unit
- `LBORNRHI` (String): Reference Range Upper Limit in Orig Unit
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBSTNRLO` (Float64): Reference Range Lower Limit-Std Units
- `LBSTNRHI` (Float64): Reference Range Upper Limit-Std Units
- `LBNRIND` (String): Reference Range Indicator
- `LBBLFL` (String): Baseline Flag
- `LBFAST` (String): Fasting Status
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lb_metabolic_meta: Final[DatasetMeta]
lb_neuro: Final[DataFrame]
"""Laboratory Test Dataset-neuro

151 rows x 23 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Int32): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBORNRLO` (String): Reference Range Lower Limit in Orig Unit
- `LBORNRHI` (String): Reference Range Upper Limit in Orig Unit
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBSTNRLO` (Float64): Reference Range Lower Limit-Std Units
- `LBSTNRHI` (Float64): Reference Range Upper Limit-Std Units
- `LBNRIND` (String): Reference Range Indicator
- `LBBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lb_neuro_meta: Final[DatasetMeta]
lb_onco_pcwg3: Final[DataFrame]
"""Laboratory Measurements (PSA) for Oncology

41 rows x 18 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Int32): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lb_onco_pcwg3_meta: Final[DatasetMeta]
mb: Final[DataFrame]
"""Microbiology Specimen

18 rows x 21 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `MBSEQ` (Int32): Sequence Number
- `MBGRPID` (Float64): Group ID
- `MBREFID` (String): Reference ID
- `MBLNKGRP` (String): Link Group ID
- `MBTESTCD` (String): Microbiology Test or Finding Short Name
- `MBTEST` (String): Microbiology Test or Finding Name
- `MBTSTDTL` (String): Measurement, Test or Examination Detail
- `MBORRES` (String): Result or Finding in Original Units
- `MBORRESU` (String): Original Units
- `MBRSLSCL` (String): Result Scale
- `MBSTRESC` (String): Result or Finding in Standard Format
- `MBSTRESN` (String): Numeric Result/Finding in Standard Units
- `MBSTRESU` (String): Standard Units
- `MBSPEC` (String): Specimen Material Type
- `MBLOC` (String): Specimen Collection Location
- `MBMETHOD` (String): Method of Test or Examination
- `VISITNUM` (Float64): Visit Number
- `MBDTC` (String): Date/Time of Collection
"""
mb_meta: Final[DatasetMeta]
mh: Final[DataFrame]
"""Medical History

1818 rows x 28 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `MHSEQ` (Float64): Sequence Number
- `MHSPID` (String): Sponsor-Defined Identifier
- `MHTERM` (String): Reported Term for the Medical History
- `MHLLT` (String): Lowest Level Term
- `MHDECOD` (String): Dictionary-Derived Term
- `MHHLT` (String): High Level Term
- `MHHLGT` (String): High Level Group Term
- `MHCAT` (String): Category for Medical History
- `MHBODSYS` (String): Body System or Organ Class
- `MHSEV` (String): Severity/Intensity
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `MHDTC` (String): Date/Time of History Collection
- `MHSTDTC` (String): Start Date/Time of Medical History Event
- `MHDY` (Float64): Study Day of History Collection
- `MHENDTC` (String): End Date/Time of Medical History Event
- `MHPRESP` (String): Medical History Event Pre-Specified
- `MHOCCUR` (String): Medical History Occurrence
- `MHSTRTPT` (String): Start Relative to Reference Time Point
- `MHENRTPT` (String): End Relative to Reference Time Point
- `MHSTTPT` (String): Start Reference Time Point
- `MHENTPT` (String): End Reference Time Point
- `MHENRF` (String): End Relative to Reference Period
- `MHSTAT` (String): Completion Status
"""
mh_meta: Final[DatasetMeta]
ms: Final[DataFrame]
"""Microbiology Susceptibility

47 rows x 23 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `MSSEQ` (Int32): Sequence Number
- `MSREFID` (String): Reference ID
- `NHOID` (String): Non-host Organism ID
- `MSGRPID` (Float64): Group ID
- `MSLNKID` (String): Link ID
- `MSTESTCD` (String): Short Name of Assessment
- `MSTEST` (String): Name of Assessment
- `MSAGENT` (String): Agent Name
- `MSCONC` (String): Agent Concentration
- `MSCONCU` (String): Agent Concentration Units
- `MSORRES` (String): Result or Finding in Original Units
- `MSORRESU` (String): Original Units
- `MSSTRESC` (String): Result or Finding in Standard Format
- `MSSTRESN` (String): Numeric Result/Finding in Standard Units
- `MSSTRESU` (String): Standard Units
- `MSSPEC` (String): Specimen Material Type
- `MSLOC` (String): Location Used for the Measurement
- `MSMETHOD` (String): Method of Test or Examination
- `VISITNUM` (Float64): Visit Number
- `MSDTC` (String): Date/Time of Collection
"""
ms_meta: Final[DatasetMeta]
nv_neuro: Final[DataFrame]
"""Neurological Assessment Dataset-neuro

98 rows x 21 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `NVSEQ` (Int32): Sequence Number
- `NVLNKID` (Float64): Link ID
- `NVTESTCD` (String): Short Name of Nervous System Test
- `NVTEST` (String): Name of Nervous System Test
- `NVCAT` (String): Category for Nervous System Test
- `NVLOC` (String): Location Used for the Measurement
- `NVMETHOD` (String): Method of Test or Examination
- `NVNAM` (String): Vendor Name
- `NVORRES` (String): Result or Finding in Original Units
- `NVORRESU` (String): Original Units
- `NVSTRESC` (String): Character Result/Finding in Std Format
- `NVSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `NVSTRESU` (String): Standard Units
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `NVDTC` (String): Date/Time of Collection
- `NVDY` (Float64): Study Day of Collection
- `NVLOBXFL` (String): Last Observation Before Exposure Flag
"""
nv_neuro_meta: Final[DatasetMeta]
oe_ophtha: Final[DataFrame]
"""Ophthalmic Examinations for Ophthalmology

26852 rows x 25 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `OESEQ` (Int32): Sequence Number
- `OECAT` (String): Category for Ophthalmic Test or Exam
- `OESCAT` (String): Subcategory for Ophthalmic Test or Exam
- `OEDTC` (String): Date/Time of Collection
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `VISITDY` (Float64): Planned Study Day of Visit
- `OESTRESN` (Float64): Numeric Result/Finding in Standard Units
- `OESTRESC` (String): Character Result/Finding in Std Format
- `OEORRES` (String): Result or Finding in Original Units
- `OETEST` (String): Name of Ophthalmic Test or Examination
- `OETESTCD` (String): Short Name of Ophthalmic Test or Exam
- `OETSTDTL` (String): Ophthalmic Test or Exam Detail
- `OELAT` (String): Laterality
- `OELOC` (String): Location Used for the Measurement
- `OEDY` (Float64): Study Day of Visit/Collection/Exam
- `OEMETHOD` (String): Method of Test or Examination
- `OEORRESU` (String): Original Units
- `OESTRESU` (String): Standard Units
- `OESTAT` (String): Completion Status
- `OETPT` (String): Planned Time Point Name
- `OETPTNUM` (Float64): Planned Time Point Number
"""
oe_ophtha_meta: Final[DatasetMeta]
pc: Final[DataFrame]
"""Pharmacokinetic Concentrations

4572 rows x 21 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `PCSEQ` (Int32): Sequence Number
- `PCTESTCD` (String): Pharmacokinetic Test Short Name
- `PCTEST` (String): Pharmacokinetic Test Name
- `PCORRES` (String): Result or Finding in Original Units
- `PCORRESU` (String): Original Units
- `PCSTRESC` (String): Character Result/Finding in Std Format
- `PCSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `PCSTRESU` (String): Standard Units
- `PCNAM` (String): Vendor Name
- `PCSPEC` (String): Specimen Material Type
- `PCLLOQ` (Float64): Lower Limit of Quantitation
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `VISITDY` (Float64): Planned Study Day of Visit
- `PCDTC` (String): Date/Time of Specimen Collection
- `PCDY` (Float64): Actual Study Day of Specimen Collection
- `PCTPT` (String): Planned Time Point Name
- `PCTPTNUM` (Float64): Planned Time Point Number
"""
pc_meta: Final[DatasetMeta]
pp: Final[DataFrame]
"""Pharmacokinetic Parameters

2688 rows x 14 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `PPSEQ` (Int32): Sequence Number
- `PPTESTCD` (String): Parameter Short Name
- `PPTEST` (String): Parameter Name
- `PPCAT` (String): Parameter Category
- `PPORRES` (Float64): Result or Finding in Original Units
- `PPORRESU` (String): Original Units
- `PPSTRESC` (Float64): Character Result/Finding in Std Format
- `PPSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `PPSTRESU` (String): Standard Units
- `PPSPEC` (String): Specimen Material Type
- `PPRFDTC` (String): Date/Time of Reference Point
"""
pp_meta: Final[DatasetMeta]
qs_metabolic: Final[DataFrame]
"""Questionnaire Dataset-metabolic

966 rows x 18 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `DOMAIN` (String): Domain Abbreviation
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `VISITDY` (Float64): Planned Study Day of Visit
- `QSBLFL` (String): Baseline Flag
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
- `QSCAT` (String): Category for Questionnaire
- `QSTEST` (String): Questionnaire Test Name
- `QSTESTCD` (String): Questionnaire Test Short Name
- `QSORRES` (String): Result or Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Character Result/Finding in Std Format
- `QSSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSEQ` (Int32): Sequence Number
"""
qs_metabolic_meta: Final[DatasetMeta]
qs_ophtha: Final[DataFrame]
"""Questionnaire for Ophthalmology

348 rows x 20 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Int32): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Character Result/Finding in Std Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qs_ophtha_meta: Final[DatasetMeta]
rs_onco: Final[DataFrame]
"""Disease Response for Oncology

5808 rows x 19 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `RSSEQ` (Int32): Sequence Number
- `RSLNKGRP` (String): Link Group
- `RSTESTCD` (String): Response Assessment Short Name
- `RSTEST` (String): Response Assessment Name
- `RSCAT` (String): Category for Response Assessment
- `RSORRES` (String): Response Assessment Original Result
- `RSSTRESC` (String): Response Assessment Result in Std Format
- `RSSTAT` (String): Completion Status
- `RSREASND` (String): Reason Response Assessment Not Performed
- `RSEVAL` (String): Evaluator
- `RSEVALID` (String): Evaluator Identifier
- `RSACPTFL` (String): Accepted Record Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `RSDTC` (String): Date/Time of Response Assessment
- `RSDY` (Float64): Study Day of Response Assessment
"""
rs_onco_meta: Final[DatasetMeta]
rs_onco_ca125: Final[DataFrame]
"""Disease Response (GCIG)

66 rows x 13 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `RSSEQ` (Int32): Sequence Number
- `RSTESTCD` (String): Assessment Short Name
- `RSTEST` (String): Assessment Name
- `RSCAT` (String): Category for Assessment
- `RSORRES` (String): Result or Finding in Original Units
- `RSSTRESC` (String): Character Result/Finding in Std Format
- `RSEVAL` (String): Evaluator
- `VISITNUM` (Int32): Visit Number
- `VISIT` (String): Visit Name
- `RSDTC` (String): Date/Time of Assessment
"""
rs_onco_ca125_meta: Final[DatasetMeta]
rs_onco_imwg: Final[DataFrame]
"""Disease Response (IMWG)

65 rows x 17 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `RSSEQ` (Int32): Sequence Number
- `RSLNKGRP` (String): Link Group ID
- `RSTESTCD` (String): Assessment Short Name
- `RSTEST` (String): Assessment Name
- `RSCAT` (String): Category for Assessment
- `RSORRES` (String): Result or Finding in Original Units
- `RSSTRESC` (String): Character Result/Finding in Std Format
- `RSSTAT` (Boolean): Completion Status
- `RSREASND` (Boolean): Reason Not Done
- `RSEVAL` (String): Evaluator
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `RSDTC` (String): Date/Time of Assessment
- `RSDY` (Int32): Study Day of Assessment
"""
rs_onco_imwg_meta: Final[DatasetMeta]
rs_onco_irecist: Final[DataFrame]
"""Disease Response (iRECIST) for Oncology

376 rows x 19 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `RSSEQ` (Int32): Sequence Number
- `RSLNKGRP` (String): Link Group ID
- `RSTESTCD` (String): Assessment Short Name
- `RSTEST` (String): Assessment Name
- `RSCAT` (String): Category for Assessment
- `RSORRES` (String): Result or Finding in Original Units
- `RSSTRESC` (String): Character Result/Finding in Std Format
- `RSSTAT` (String): Completion Status
- `RSREASND` (String): Reason Not Done
- `RSEVAL` (String): Evaluator
- `RSEVALID` (String): Evaluator Identifier
- `RSACPTFL` (String): Accepted Record Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `RSDTC` (String): Date/Time of Assessment
- `RSDY` (Int32): Study Day of Assessment
"""
rs_onco_irecist_meta: Final[DatasetMeta]
rs_onco_lymphoma: Final[DataFrame]
"""Disease Response (Lymphoma Lugano 2014)

68 rows x 17 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `RSSEQ` (Int32): Sequence Number
- `RSTESTCD` (String): Response Assessment Short Name
- `RSTEST` (String): Response Assessment Name
- `RSCAT` (String): Category for Response Assessment
- `RSMETHOD` (String): undocumented field
- `RSSCAT` (String): undocumented field
- `RSORRES` (String): Response Assessment Original Result
- `RSSTRESC` (String): Response Assessment Result in Std Format
- `RSSTAT` (String): Completion Status
- `RSEVAL` (String): Evaluator
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `RSDTC` (String): Date/Time of Response Assessment
- `RSDY` (Float64): Study Day of Response Assessment
"""
rs_onco_lymphoma_meta: Final[DatasetMeta]
rs_onco_pcwg3: Final[DataFrame]
"""Disease Response (PCWG3) for Oncology

90 rows x 14 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `RSSEQ` (Int32): Sequence Number
- `RSTESTCD` (String): Response Assessment Short Name
- `RSTEST` (String): Response Assessment Name
- `RSCAT` (String): Category for Response Assessment
- `RSORRES` (String): Response Assessment Original Result
- `RSSTRESC` (String): Response Assessment Result in Std Format
- `RSEVAL` (String): Evaluator
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `RSDTC` (String): Date/Time of Response Assessment
- `RSDY` (Float64): Study Day of Response Assessment
"""
rs_onco_pcwg3_meta: Final[DatasetMeta]
rs_onco_recist: Final[DataFrame]
"""Disease Response (RECIST 1.1) for Oncology

66 rows x 14 columns.

Variables:

- `DOMAIN` (String): Domain Abbreviation
- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `RSTESTCD` (String): Assessment Short Name
- `RSTEST` (String): Assessment Name
- `RSORRES` (String): Result or Finding in Original Units
- `RSSTRESC` (String): Character Result/Finding in Std Format
- `RSEVAL` (String): Evaluator
- `RSEVALID` (String): Evaluator Identifier
- `RSACPTFL` (String): Accepted Record Flag
- `RSDTC` (String): Date/Time of Assessment
- `RSSEQ` (Int32): Sequence Number
"""
rs_onco_recist_meta: Final[DatasetMeta]
sc_ophtha: Final[DataFrame]
"""Subject Characteristic for Ophthalmology

254 rows x 12 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SCSEQ` (Int32): Sequence Number
- `SCTESTCD` (String): Subject Characteristic Short Name
- `SCTEST` (String): Subject Characteristic
- `SCCAT` (String): Category for Subject Characteristic
- `SCORRES` (String): Result or Finding in Original Units
- `SCSTRESC` (String): Character Result/Finding in Std Format
- `EPOCH` (String): Epoch
- `SCDTC` (String): Date/Time of Collection
- `SCDY` (Float64): Study Day of Examination
"""
sc_ophtha_meta: Final[DatasetMeta]
sdg_db: Final[DataFrame]
"""SDG

16 rows x 5 columns.

Variables:

- `termchar` (String): Reported Term
- `sdg_name` (String): Name
- `sdg_id` (Int32): Name ID
- `termvar` (String): Variable
- `version` (String): Version
"""
sdg_db_meta: Final[DatasetMeta]
smq_db: Final[DataFrame]
"""Standardized MedDRA Queries

44 rows x 6 columns.

Variables:

- `termchar` (String): Reported Term
- `scope` (String): Scope
- `smq_name` (String): Name
- `smq_id` (Int32): Name ID
- `version` (String): Version
- `termvar` (String): Variable
"""
smq_db_meta: Final[DatasetMeta]
suppae: Final[DataFrame]
"""Supplemental Adverse Events

1191 rows x 10 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
suppae_meta: Final[DatasetMeta]
suppce_vaccine: Final[DataFrame]
"""Supplemental Qualifiers for Clinical Events for Vaccine

4 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QVAL` (String): Data Value
- `QLABEL` (String): Qualifier Variable Label
- `QORIG` (String): Origin
"""
suppce_vaccine_meta: Final[DatasetMeta]
suppdm: Final[DataFrame]
"""Supplemental Demography

1197 rows x 10 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
suppdm_meta: Final[DatasetMeta]
suppdm_vaccine: Final[DataFrame]
"""Supplemental Qualifiers for Demographics for Vaccine

2 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QVAL` (String): Data Value
- `QLABEL` (String): Qualifier Variable Label
- `QORIG` (String): Origin
"""
suppdm_vaccine_meta: Final[DatasetMeta]
suppds: Final[DataFrame]
"""Supplemental Disposition

3 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
"""
suppds_meta: Final[DatasetMeta]
suppex_vaccine: Final[DataFrame]
"""Supplemental Qualifiers for Exposures for Vaccine

4 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QVAL` (String): Data Value
- `QLABEL` (String): Qualifier Variable Label
- `QORIG` (String): Origin
"""
suppex_vaccine_meta: Final[DatasetMeta]
suppface_vaccine: Final[DataFrame]
"""Supplemental Qualifiers for Findings About for Clinical Events for Vaccine

4 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QVAL` (String): Data Value
- `QLABEL` (String): Qualifier Variable Label
- `QORIG` (String): Origin
"""
suppface_vaccine_meta: Final[DatasetMeta]
suppis_vaccine: Final[DataFrame]
"""Supplemental Qualifiers for Immunogenicity Specimen Assessments for Vaccine

16 rows x 10 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (Boolean): Evaluator
"""
suppis_vaccine_meta: Final[DatasetMeta]
suppnv_neuro: Final[DataFrame]
"""Supplemental for Neurological Assessment Dataset-neuro

68 rows x 10 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (Int32): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
suppnv_neuro_meta: Final[DatasetMeta]
supprs_onco_ca125: Final[DataFrame]
"""Supplemental Qualifiers for RS_ONCO_CA125

49 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
"""
supprs_onco_ca125_meta: Final[DatasetMeta]
supprs_onco_imwg: Final[DataFrame]
"""Supplemental Qualifiers for RS_ONCO_IMWG

19 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
"""
supprs_onco_imwg_meta: Final[DatasetMeta]
supptr_onco: Final[DataFrame]
"""Supplemental Tumor Results for Oncology

55995 rows x 9 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
"""
supptr_onco_meta: Final[DatasetMeta]
sv: Final[DataFrame]
"""Subject Visits

3559 rows x 8 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `SVSTDTC` (String): Start Date/Time of Visit
- `SVENDTC` (String): End Date/Time of Visit
"""
sv_meta: Final[DatasetMeta]
tr_onco: Final[DataFrame]
"""Tumor Results for Oncology

55995 rows x 24 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `TRSEQ` (Int32): Sequence Number
- `TRGRPID` (String): Group ID
- `TRLNKGRP` (String): Link Group
- `TRLNKID` (String): Link ID
- `TRTESTCD` (String): Tumor Assessment Short Name
- `TRTEST` (String): Tumor Assessment Test Name
- `TRORRES` (String): Result or Finding in Original Units
- `TRORRESU` (String): Original Units
- `TRSTRESC` (String): Character Result/Finding in Std Format
- `TRSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `TRSTRESU` (String): Standard Units
- `TRSTAT` (String): Completion Status
- `TRREASND` (String): Reason Tumor Measurement Not Performed
- `TRMETHOD` (String): Method used to Identify the Tumor
- `TREVAL` (String): Evaluator
- `TREVALID` (String): Evaluator Identifier
- `TRACPTFL` (String): Accepted Record Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `TRDTC` (String): Date/Time of Tumor Measurement
- `TRDY` (Float64): Study Day of Tumor Measurement
"""
tr_onco_meta: Final[DatasetMeta]
tr_onco_recist: Final[DataFrame]
"""Tumor Results (RECIST 1.1) for Oncology

546 rows x 19 columns.

Variables:

- `DOMAIN` (String): Domain Abbreviation
- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `TRGRPID` (String): Group ID
- `TRLNKID` (String): Link ID
- `TRTESTCD` (String): Tumor/Lesion Assessment Short Name
- `TRTEST` (String): Tumor/Lesion Assessment Test Name
- `TRORRES` (String): Result or Finding in Original Units
- `TRORRESU` (String): Original Units
- `TRSTRESC` (String): Character Result/Finding in Std Format
- `TRSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `TRSTRESU` (String): Standard Units
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `TREVAL` (String): Evaluator
- `TREVALID` (String): Evaluator Identifier
- `TRACPTFL` (String): Accepted Record Flag
- `TRDTC` (String): Date/Time of Tumor/Lesion Measurement
- `TRSEQ` (Int32): Sequence Number
"""
tr_onco_recist_meta: Final[DatasetMeta]
ts: Final[DataFrame]
"""Trial Design

33 rows x 6 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `TSSEQ` (Float64): Sequence Number
- `TSPARMCD` (String): Trial Summary Parameter Short Name
- `TSPARM` (String): Trial Summary Parameter
- `TSVAL` (String): Parameter Value
"""
ts_meta: Final[DatasetMeta]
tu_onco: Final[DataFrame]
"""Tumor Identification for Oncology

7734 rows x 18 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `TUSEQ` (Int32): Sequence Number
- `TULNKID` (String): Link ID
- `TUTESTCD` (String): Tumor Identification Short Name
- `TUTEST` (String): Tumor Identification Test Name
- `TUORRES` (String): Tumor Identification Result
- `TUSTRESC` (String): Tumor Identification Result Std. Format
- `TULOC` (String): Location of the Tumor
- `TUMETHOD` (String): Method of Identification
- `TUEVAL` (String): Evaluator
- `TUEVALID` (String): Evaluator Identifier
- `TUACPTFL` (String): Accepted Record Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `TUDTC` (String): Date/Time of Tumor Identification
- `TUDY` (Float64): Study Day of Tumor Identification
"""
tu_onco_meta: Final[DatasetMeta]
tu_onco_recist: Final[DataFrame]
"""Tumor Identification (RECIST 1.1) for Oncology

75 rows x 16 columns.

Variables:

- `DOMAIN` (String): Domain Abbreviation
- `STUDYID` (String): Study Identifier
- `USUBJID` (String): Unique Subject Identifier
- `VISIT` (String): Visit Name
- `VISITNUM` (Float64): Visit Number
- `TULOC` (String): Location of the Tumor/Lesion
- `TUTESTCD` (String): Tumor/Lesion ID Short Name
- `TUTEST` (String): Tumor/Lesion ID Test Name
- `TUORRES` (String): Tumor/Lesion ID Result
- `TUSTRESC` (String): Tumor/Lesion ID Result Std. Format
- `TUMETHOD` (String): Method of Identification
- `TULNKID` (String): Link ID
- `TUEVAL` (String): Evaluator
- `TUEVALID` (String): Evaluator Identifier
- `TUACPTFL` (String): Accepted Record Flag
- `TUSEQ` (Int32): Sequence Number
"""
tu_onco_recist_meta: Final[DatasetMeta]
vs: Final[DataFrame]
"""Vital Signs

29643 rows x 24 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VSSEQ` (Float64): Sequence Number
- `VSTESTCD` (String): Vital Signs Test Short Name
- `VSTEST` (String): Vital Signs Test Name
- `VSPOS` (String): Vital Signs Position of Subject
- `VSORRES` (String): Result or Finding in Original Units
- `VSORRESU` (String): Original Units
- `VSSTRESC` (String): Character Result/Finding in Std Format
- `VSSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `VSSTRESU` (String): Standard Units
- `VSSTAT` (String): Completion Status
- `VSLOC` (String): Location of Vital Signs Measurement
- `VSBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `VSDTC` (String): Date/Time of Measurements
- `VSDY` (Float64): Study Day of Vital Signs
- `VSTPT` (String): Planned Time Point Name
- `VSTPTNUM` (Float64): Planned Time Point Number
- `VSELTM` (String): Planned Elapsed Time from Time Point Ref
- `VSTPTREF` (String): Time Point Reference
"""
vs_meta: Final[DatasetMeta]
vs_metabolic: Final[DataFrame]
"""Vital signs Dataset-metabolic

719 rows x 24 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VSSEQ` (Int32): Sequence Number
- `VSTESTCD` (String): Vital Signs Test Short Name
- `VSTEST` (String): Vital Signs Test Name
- `VSPOS` (String): Vital Signs Position of Subject
- `VSORRES` (String): Result or Finding in Original Units
- `VSORRESU` (String): Original Units
- `VSSTRESC` (String): Character Result/Finding in Std Format
- `VSSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `VSSTRESU` (String): Standard Units
- `VSSTAT` (String): Completion Status
- `VSLOC` (String): Location of Vital Signs Measurement
- `VSBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `VSDTC` (String): Date/Time of Measurements
- `VSDY` (Float64): Study Day of Vital Signs
- `VSTPT` (String): Planned Time Point Name
- `VSTPTNUM` (Float64): Planned Time Point Number
- `VSELTM` (String): Planned Elapsed Time from Time Point Ref
- `VSTPTREF` (String): Time Point Reference
"""
vs_metabolic_meta: Final[DatasetMeta]
vs_peds: Final[DataFrame]
"""Vital signs Dataset-pediatrics

164 rows x 26 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VSSEQ` (Int32): Sequence Number
- `VSTESTCD` (String): Vital Signs Test Short Name
- `VSTEST` (String): Vital Signs Test Name
- `VSPOS` (String): Vital Signs Position of Subject
- `VSORRES` (String): Result or Finding in Original Units
- `VSORRESU` (String): Original Units
- `VSSTRESC` (String): Character Result/Finding in Std Format
- `VSSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `VSSTRESU` (String): Standard Units
- `VSSTAT` (String): Completion Status
- `VSLOC` (String): Location of Vital Signs Measurement
- `VSBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Int32): Planned Study Day of Visit
- `VSDTC` (String): Date/Time of Measurements
- `VSDY` (Int32): Study Day of Vital Signs
- `VSTPT` (String): Planned Time Point Name
- `VSTPTNUM` (Float64): Planned Time Point Number
- `VSELTM` (String): Planned Elapsed Time from Time Point Ref
- `VSTPTREF` (String): Time Point Reference
- `VSEVAL` (String): Evaluator
- `EPOCH` (String): Epoch
"""
vs_peds_meta: Final[DatasetMeta]
vs_vaccine: Final[DataFrame]
"""Vital Signs for Vaccine

28 rows x 23 columns.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VSSEQ` (Int32): Sequence Number
- `VSLNKID` (String): Link ID
- `VSLNKGRP` (String): Link Group ID
- `VSTESTCD` (String): Vital Signs Test Short Name
- `VSTEST` (String): Vital Signs Test Name
- `VSCAT` (String): Category for Vital Signs
- `VSSCAT` (String): Subcategory for Vital Signs
- `VSORRES` (String): Result or Finding in Original Units
- `VSORRESU` (String): Original Units
- `VSSTRESC` (String): Character Result/Finding in Std Format
- `VSSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `VSSTRESU` (String): Standard Units
- `VSEVAL` (String): Evaluator
- `VSLOC` (Boolean): Location of Vital Signs Measurement
- `EPOCH` (String): Epoch
- `VSDTC` (String): Date/Time of Measurements
- `VSDY` (Float64): Study Day of Vital Signs
- `VSTPT` (String): Planned Time Point Name
- `VSTPTNUM` (Int32): Planned Time Point Number
- `VSTPTREF` (String): Time Point Reference
"""
vs_vaccine_meta: Final[DatasetMeta]
