"""SDTM datasets from the CDISC SDTM/ADaM Pilot Project, lazily loaded as polars DataFrames.

Access a dataset as a module attribute, e.g. ``cdiscpilotsdtm.dm``; its metadata
as ``cdiscpilotsdtm.dm_meta`` or via ``meta(name)``.
"""

# Generated by data-raw/04_build_modules.py - do not edit.

from __future__ import annotations

from typing import TYPE_CHECKING

from pharmadata._core import collection, data
from pharmadata._core.meta import DatasetMeta, build

if TYPE_CHECKING:
    import pandas as pd
    import polars as pl
    import pyarrow as pa


def list_datasets() -> list[str]:
    """Names of the available SDTM datasets, sorted alphabetically.

    Returns
    -------
    list[str]
        A list of dataset names.

    Examples
    --------
    >>> "dm" in cdiscpilotsdtm.list_datasets()
    True
    """
    return data.list_datasets("cdiscpilotsdtm")


def meta(name: str) -> DatasetMeta:
    """pyreadstat-style metadata of a dataset.

    Parameters
    ----------
    name : str
        The dataset name, e.g. ``"dm"``.

    Returns
    -------
    DatasetMeta
        The metadata object the ``<name>_meta`` module attribute serves.

    Raises
    ------
    ValueError
        If *name* is not a known SDTM dataset.

    Examples
    --------
    >>> cdiscpilotsdtm.meta("dm").column_names_to_labels["STUDYID"]
    'Study Identifier'
    """
    return build("cdiscpilotsdtm", name)


def meta_tables() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Dataset-level metadata: one row per dataset.

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per dataset, in the active output format, with the columns
        ``dataset, label, n_rows, n_cols``.

    Examples
    --------
    >>> cdiscpilotsdtm.meta_tables().columns
    ['dataset', 'label', 'n_rows', 'n_cols']
    """
    return data.meta_tables("cdiscpilotsdtm")


def meta_columns() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Column-level metadata of every SDTM dataset (long format).

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per column of every dataset, in the active output format,
        with the columns ``dataset, variable, label, type``.

    Examples
    --------
    >>> cdiscpilotsdtm.meta_columns().columns
    ['dataset', 'variable', 'label', 'type']
    """
    return data.meta_columns("cdiscpilotsdtm")


def meta_specs() -> pa.Table | pl.DataFrame | pd.DataFrame:
    """Column-level specifications of every SDTM dataset (long format).

    Returns
    -------
    pa.Table or pl.DataFrame or pd.DataFrame
        One row per variable, in the active output format, with the columns
        ``dataset, variable, label, type, mandatory, role``.

    Examples
    --------
    >>> cdiscpilotsdtm.meta_specs().columns
    ['dataset', 'variable', 'label', 'type', 'mandatory', 'role']
    """
    return data.meta_specs("cdiscpilotsdtm")


def to_dict() -> dict[str, pa.Table | pl.DataFrame | pd.DataFrame]:
    """Every SDTM dataset loaded at once, keyed by name.

    Reads the whole collection, so prefer the lazy attributes (e.g.
    ``cdiscpilotsdtm.dm``) when only a few datasets are needed. Honors the active
    output format: with ``output_format="pandas"`` the values are pandas DataFrames.

    Returns
    -------
    dict[str, pa.Table | pl.DataFrame | pd.DataFrame]
        One entry per dataset, mapping each dataset name to its frame in the
        active output format.

    Examples
    --------
    >>> "dm" in cdiscpilotsdtm.to_dict()
    True
    """
    return collection.load_all("cdiscpilotsdtm")


collection.install(__name__, data.COLLECTIONS["cdiscpilotsdtm"])
