# Generated by data-raw/04_build_modules.py - do not edit.
from typing import Final

from pandas import DataFrame as PandasDataFrame
from polars import DataFrame
from pyarrow import Table

from pharmadata import DatasetMeta

def list_datasets() -> list[str]: ...
def meta(name: str) -> DatasetMeta: ...
def meta_tables() -> DataFrame | Table | PandasDataFrame: ...
def meta_columns() -> DataFrame | Table | PandasDataFrame: ...
def meta_specs() -> DataFrame | Table | PandasDataFrame: ...
def to_dict() -> dict[str, DataFrame | Table | PandasDataFrame]: ...

# Datasets are lazy attributes (module __getattr__); Final mirrors that
# to a static checker.
ae: Final[DataFrame]
"""Adverse Events

961 rows x 37 columns.
Structure: One record per adverse event per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `AESEQ` (Float64): Sequence Number
- `AESPID` (String): Sponsor-Defined Identifier
- `AETERM` (String): Reported Term for the Adverse Event
- `AELLT` (String): Lowest Level Term
- `AELLTCD` (Float64): Lowest Level Term Code
- `AEDECOD` (String): Dictionary-Derived Term
- `AEPTCD` (Float64): Preferred Term Code
- `AEHLT` (String): High Level Term
- `AEHLTCD` (Float64): High Level Term Code
- `AEHLGT` (String): High Level Group Term
- `AEHLGTCD` (Float64): High Level Group Term Code
- `AEBODSYS` (String): Body System or Organ Class
- `AEBDSYCD` (Float64): Body System or Organ Class Code
- `AESOC` (String): Primary System Organ Class
- `AESOCCD` (Float64): Primary System Organ Class Code
- `AESEV` (String): Severity/Intensity
- `AESER` (String): Serious Event
- `AEACN` (String): Action Taken with Study Treatment
- `AEREL` (String): Causality
- `AEOUT` (String): Outcome of Adverse Event
- `AESCAN` (String): Involves Cancer
- `AESCONG` (String): Congenital Anomaly or Birth Defect
- `AESDISAB` (String): Persist or Signif Disability/Incapacity
- `AESDTH` (String): Results in Death
- `AESHOSP` (String): Requires or Prolongs Hospitalization
- `AESLIFE` (String): Is Life Threatening
- `AESOD` (String): Occurred with Overdose
- `EPOCH` (String): Epoch
- `AEDTC` (String): Date/Time of Collection
- `AESTDTC` (String): Start Date/Time of Adverse Event
- `AEENDTC` (String): End Date/Time of Adverse Event
- `AEDY` (Float64): Study Day of Visit/Collection/Exam
- `AESTDY` (Float64): Study Day of Start of Adverse Event
- `AEENDY` (Float64): Study Day of End of Adverse Event
"""
ae_meta: Final[DatasetMeta]
cm: Final[DataFrame]
"""Concomitant Medications

7510 rows x 23 columns.
Structure: One record per recorded medication occurrence or constant-dosing interval per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `CMSEQ` (Float64): Sequence Number
- `CMSPID` (String): Sponsor-Defined Identifier
- `CMTRT` (String): Reported Name of Drug, Med, or Therapy
- `CMDECOD` (String): Standardized Medication Name
- `CMINDC` (String): Indication
- `CMCLAS` (String): Medication Class
- `CMDOSE` (Float64): Dose per Administration
- `CMDOSU` (String): Dose Units
- `CMDOSFRQ` (String): Dosing Frequency per Interval
- `CMROUTE` (String): Route of Administration
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `CMDTC` (String): Date/Time of Collection
- `CMSTDTC` (String): Start Date/Time of Medication
- `CMENDTC` (String): End Date/Time of Medication
- `CMDY` (Float64): Study Day of Visit/Collection/Exam
- `CMSTDY` (Float64): Study Day of Start of Medication
- `CMENDY` (Float64): Study Day of End of Medication
"""
cm_meta: Final[DatasetMeta]
dm: Final[DataFrame]
"""Demographics

306 rows x 25 columns.
Structure: One record per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SUBJID` (String): Subject Identifier for the Study
- `RFSTDTC` (String): Subject Reference Start Date/Time
- `RFENDTC` (String): Subject Reference End Date/Time
- `RFXSTDTC` (String): Date/Time of First Study Treatment
- `RFXENDTC` (String): Date/Time of Last Study Treatment
- `RFICDTC` (String): Date/Time of Informed Consent
- `RFPENDTC` (String): Date/Time of End of Participation
- `DTHDTC` (String): Date/Time of Death
- `DTHFL` (String): Subject Death Flag
- `SITEID` (String): Study Site Identifier
- `AGE` (Float64): Age
- `AGEU` (String): Age Units
- `SEX` (String): Sex
- `RACE` (String): Race
- `ETHNIC` (String): Ethnicity
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `ACTARMCD` (String): Actual Arm Code
- `ACTARM` (String): Description of Actual Arm
- `COUNTRY` (String): Country
- `DMDTC` (String): Date/Time of Collection
- `DMDY` (Float64): Study Day of Collection
"""
dm_meta: Final[DatasetMeta]
ds: Final[DataFrame]
"""Disposition

596 rows x 15 columns.
Structure: One record per disposition status or protocol milestone per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `DSSEQ` (Float64): Sequence Number
- `DSSPID` (String): Sponsor-Defined Identifier
- `DSTERM` (String): Reported Term for the Disposition Event
- `DSDECOD` (String): Standardized Disposition Term
- `DSCAT` (String): Category for Disposition Event
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `EPOCH` (String): Epoch
- `DSDTC` (String): Date/Time of Collection
- `DSSTDTC` (String): Start Date/Time of Disposition Event
- `DSDY` (Float64): Study Day of Visit/Collection/Exam
- `DSSTDY` (Float64): Study Day of Start of Disposition Event
"""
ds_meta: Final[DatasetMeta]
ex: Final[DataFrame]
"""Exposure

591 rows x 18 columns.
Structure: One record per constant dosing interval per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `EXSEQ` (Float64): Sequence Number
- `EXTRT` (String): Name of Treatment
- `EXDOSE` (Float64): Dose
- `EXDOSU` (String): Dose Units
- `EXDOSFRM` (String): Dose Form
- `EXDOSFRQ` (String): Dosing Frequency per Interval
- `EXROUTE` (String): Route of Administration
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `EXSTDTC` (String): Start Date/Time of Treatment
- `EXENDTC` (String): End Date/Time of Treatment
- `EXSTDY` (Float64): Study Day of Start of Treatment
- `EXENDY` (Float64): Study Day of End of Treatment
"""
ex_meta: Final[DatasetMeta]
lbch: Final[DataFrame]
"""Laboratory Tests Results

32740 rows x 24 columns.
Structure: One record per analyte per planned time point number per time point reference per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Float64): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBORNRLO` (String): Reference Range Lower Limit in Orig Unit
- `LBORNRHI` (String): Reference Range Upper Limit in Orig Unit
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBSTNRLO` (Float64): Reference Range Lower Limit-Std Units
- `LBSTNRHI` (Float64): Reference Range Upper Limit-Std Units
- `LBNRIND` (String): Reference Range Indicator
- `LBBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lbch_meta: Final[DatasetMeta]
lbhe: Final[DataFrame]
"""Laboratory Tests Results

21927 rows x 24 columns.
Structure: One record per analyte per planned time point number per time point reference per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Float64): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBORNRLO` (String): Reference Range Lower Limit in Orig Unit
- `LBORNRHI` (String): Reference Range Upper Limit in Orig Unit
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBSTNRLO` (Float64): Reference Range Lower Limit-Std Units
- `LBSTNRHI` (Float64): Reference Range Upper Limit-Std Units
- `LBNRIND` (String): Reference Range Indicator
- `LBBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lbhe_meta: Final[DatasetMeta]
lbur: Final[DataFrame]
"""Laboratory Tests Results

4913 rows x 24 columns.
Structure: One record per analyte per planned time point number per time point reference per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `LBSEQ` (Float64): Sequence Number
- `LBTESTCD` (String): Lab Test or Examination Short Name
- `LBTEST` (String): Lab Test or Examination Name
- `LBCAT` (String): Category for Lab Test
- `LBORRES` (String): Result or Finding in Original Units
- `LBORRESU` (String): Original Units
- `LBORNRLO` (String): Reference Range Lower Limit in Orig Unit
- `LBORNRHI` (String): Reference Range Upper Limit in Orig Unit
- `LBSTRESC` (String): Character Result/Finding in Std Format
- `LBSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `LBSTRESU` (String): Standard Units
- `LBSTNRLO` (Float64): Reference Range Lower Limit-Std Units
- `LBSTNRHI` (Float64): Reference Range Upper Limit-Std Units
- `LBNRIND` (String): Reference Range Indicator
- `LBBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `LBDTC` (String): Date/Time of Specimen Collection
- `LBDY` (Float64): Study Day of Specimen Collection
"""
lbur_meta: Final[DatasetMeta]
mh: Final[DataFrame]
"""Medical History

1817 rows x 19 columns.
Structure: One record per medical history event per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `MHSEQ` (Float64): Sequence Number
- `MHSPID` (String): Sponsor-Defined Identifier
- `MHTERM` (String): Reported Term for the Medical History
- `MHLLT` (String): Lowest Level Term
- `MHDECOD` (String): Dictionary-Derived Term
- `MHHLT` (String): High Level Term
- `MHHLGT` (String): High Level Group Term
- `MHCAT` (String): Category for Medical History
- `MHBODSYS` (String): Body System or Organ Class
- `MHSEV` (String): Severity/Intensity
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `MHDTC` (String): Date/Time of History Collection
- `MHSTDTC` (String): Start Date/Time of Medical History Event
- `MHDY` (Float64): Study Day of History Collection
"""
mh_meta: Final[DatasetMeta]
qsco: Final[DataFrame]
"""Questionnaires

12241 rows x 23 columns.
Structure: One record per questionnaire per question per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Float64): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Result or Finding in Standard Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSTAT` (String): Completion Status
- `QSREASND` (String): Reason Not Performed
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qsco_meta: Final[DatasetMeta]
qsda: Final[DataFrame]
"""Questionnaires

32920 rows x 23 columns.
Structure: One record per questionnaire per question per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Float64): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Result or Finding in Standard Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSTAT` (String): Completion Status
- `QSREASND` (String): Reason Not Performed
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qsda_meta: Final[DatasetMeta]
qsgi: Final[DataFrame]
"""Questionnaires

562 rows x 23 columns.
Structure: One record per questionnaire per question per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Float64): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Result or Finding in Standard Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSTAT` (String): Completion Status
- `QSREASND` (String): Reason Not Performed
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qsgi_meta: Final[DatasetMeta]
qshi: Final[DataFrame]
"""Questionnaires

3302 rows x 23 columns.
Structure: One record per questionnaire per question per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Float64): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Result or Finding in Standard Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSTAT` (String): Completion Status
- `QSREASND` (String): Reason Not Performed
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qshi_meta: Final[DatasetMeta]
qsmm: Final[DataFrame]
"""Questionnaires

1524 rows x 23 columns.
Structure: One record per questionnaire per question per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Float64): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Result or Finding in Standard Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSTAT` (String): Completion Status
- `QSREASND` (String): Reason Not Performed
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qsmm_meta: Final[DatasetMeta]
qsni: Final[DataFrame]
"""Questionnaires

71200 rows x 23 columns.
Structure: One record per questionnaire per question per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `QSSEQ` (Float64): Sequence Number
- `QSTESTCD` (String): Question Short Name
- `QSTEST` (String): Question Name
- `QSCAT` (String): Category of Question
- `QSSCAT` (String): Subcategory for Question
- `QSORRES` (String): Finding in Original Units
- `QSORRESU` (String): Original Units
- `QSSTRESC` (String): Result or Finding in Standard Format
- `QSSTRESN` (Float64): Numeric Finding in Standard Units
- `QSSTRESU` (String): Standard Units
- `QSSTAT` (String): Completion Status
- `QSREASND` (String): Reason Not Performed
- `QSBLFL` (String): Baseline Flag
- `QSDRVFL` (String): Derived Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `QSDTC` (String): Date/Time of Finding
- `QSDY` (Float64): Study Day of Finding
"""
qsni_meta: Final[DatasetMeta]
relrec: Final[DataFrame]
"""Related Records

211 rows x 7 columns.
Structure: One record per related record, group of records or datasets.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `RELTYPE` (String): Relationship Type
- `RELID` (String): Relationship Identifier
"""
relrec_meta: Final[DatasetMeta]
sc: Final[DataFrame]
"""Subject Characteristics

254 rows x 14 columns.
Structure: One record per characteristic per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SCSEQ` (Float64): Sequence Number
- `SCTESTCD` (String): Subject Characteristic Short Name
- `SCTEST` (String): Subject Characteristic
- `SCCAT` (String): Category for Subject Characteristic
- `SCORRES` (String): Result or Finding in Original Units
- `SCORRESU` (String): Original Units
- `SCSTRESC` (String): Character Result/Finding in Std Format
- `SCSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `SCSTRESU` (String): Standard Units
- `SCDTC` (String): Date/Time of Collection
- `SCDY` (Float64): Study Day of Examination
"""
sc_meta: Final[DatasetMeta]
se: Final[DataFrame]
"""Subject Elements

752 rows x 12 columns.
Structure: One record per actual Element per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `SESEQ` (Float64): Sequence Number
- `ETCD` (String): Element Code
- `ELEMENT` (String): Description of Element
- `SEUPDES` (String): Description of Unplanned Element
- `EPOCH` (String): Epoch
- `SESTDTC` (String): Start Date/Time of Element
- `SEENDTC` (String): End Date/Time of Element
- `SESTDY` (Float64): Study Day of Start of Observation
- `SEENDY` (Float64): Study Day of End of Observation
"""
se_meta: Final[DatasetMeta]
suppae: Final[DataFrame]
"""Supplemental Qualifiers for AE

961 rows x 10 columns.
Structure: One record per IDVAR, IDVARVAL, and QNAM value per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
suppae_meta: Final[DatasetMeta]
suppdm: Final[DataFrame]
"""Supplemental Qualifiers for DM

1197 rows x 10 columns.
Structure: One record per IDVAR, IDVARVAL, and QNAM value per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
suppdm_meta: Final[DatasetMeta]
suppds: Final[DataFrame]
"""Supplemental Qualifiers for DS

3 rows x 10 columns.
Structure: One record per IDVAR, IDVARVAL, and QNAM value per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
suppds_meta: Final[DatasetMeta]
supplbch: Final[DataFrame]
"""Supplemental Qualifiers for LB

37124 rows x 10 columns.
Structure: One record per IDVAR, IDVARVAL, and QNAM value per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
supplbch_meta: Final[DatasetMeta]
supplbhe: Final[DataFrame]
"""Supplemental Qualifiers for LB

24558 rows x 10 columns.
Structure: One record per IDVAR, IDVARVAL, and QNAM value per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
supplbhe_meta: Final[DatasetMeta]
supplbur: Final[DataFrame]
"""Supplemental Qualifiers for LB

2721 rows x 10 columns.
Structure: One record per IDVAR, IDVARVAL, and QNAM value per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `RDOMAIN` (String): Related Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `IDVAR` (String): Identifying Variable
- `IDVARVAL` (String): Identifying Variable Value
- `QNAM` (String): Qualifier Variable Name
- `QLABEL` (String): Qualifier Variable Label
- `QVAL` (String): Data Value
- `QORIG` (String): Origin
- `QEVAL` (String): Evaluator
"""
supplbur_meta: Final[DatasetMeta]
sv: Final[DataFrame]
"""Subject Visits

3559 rows x 12 columns.
Structure: One record per actual visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `SVSTDTC` (String): Start Date/Time of Visit
- `SVENDTC` (String): End Date/Time of Visit
- `SVSTDY` (Float64): Study Day of Start of Visit
- `SVENDY` (Float64): Study Day of End of Visit
- `SVUPDES` (String): Description of Unplanned Visit
"""
sv_meta: Final[DatasetMeta]
ta: Final[DataFrame]
"""Trial Arms

11 rows x 10 columns.
Structure: One record per planned Element per Arm.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `ARMCD` (String): Planned Arm Code
- `ARM` (String): Description of Planned Arm
- `TAETORD` (Float64): Planned Order of Element within Arm
- `ETCD` (String): Element Code
- `ELEMENT` (String): Description of Element
- `TABRANCH` (String): Branch
- `TATRANS` (String): Transition Rule
- `EPOCH` (String): Epoch
"""
ta_meta: Final[DatasetMeta]
te: Final[DataFrame]
"""Trial Elements

7 rows x 7 columns.
Structure: One record per planned Element.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `ETCD` (String): Element Code
- `ELEMENT` (String): Description of Element
- `TESTRL` (String): Rule for Start of Element
- `TEENRL` (String): Rule for End of Element
- `TEDUR` (String): Planned Duration of Element
"""
te_meta: Final[DatasetMeta]
ti: Final[DataFrame]
"""Trial Inclusion/ Exclusion Criteria

31 rows x 5 columns.
Structure: One record per I/E criterion.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `IETESTCD` (String): Inclusion/Exclusion Criterion Short Name
- `IETEST` (String): Inclusion/Exclusion Criterion
- `IECAT` (String): Inclusion/Exclusion Category
"""
ti_meta: Final[DatasetMeta]
ts: Final[DataFrame]
"""Trial Summary

48 rows x 10 columns.
Structure: One record per trial summary parameter value.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `TSSEQ` (Float64): Sequence Number
- `TSPARMCD` (String): Trial Summary Parameter Short Name
- `TSPARM` (String): Trial Summary Parameter
- `TSVAL` (String): Parameter Value
- `TSVALNF` (String): Parameter Null Flavor
- `TSVALCD` (String): Parameter Value Code
- `TSVCDREF` (String): Name of the Reference Terminology
- `TSVCDVER` (String): Version of the Reference Terminology
"""
ts_meta: Final[DatasetMeta]
tv: Final[DataFrame]
"""Trial Visits

21 rows x 8 columns.
Structure: One record per planned Visit per Arm.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `ARMCD` (String): Planned Arm Code
- `TVSTRL` (String): Visit Start Rule
- `TVENRL` (String): Visit End Rule
"""
tv_meta: Final[DatasetMeta]
vs: Final[DataFrame]
"""Vital Signs

29643 rows x 25 columns.
Structure: One record per vital sign measurement per time point per visit per subject.

Variables:

- `STUDYID` (String): Study Identifier
- `DOMAIN` (String): Domain Abbreviation
- `USUBJID` (String): Unique Subject Identifier
- `VSSEQ` (Float64): Sequence Number
- `VSTESTCD` (String): Vital Signs Test Short Name
- `VSTEST` (String): Vital Signs Test Name
- `VSPOS` (String): Vital Signs Position of Subject
- `VSORRES` (String): Result or Finding in Original Units
- `VSORRESU` (String): Original Units
- `VSSTRESC` (String): Character Result/Finding in Std Format
- `VSSTRESN` (Float64): Numeric Result/Finding in Standard Units
- `VSSTRESU` (String): Standard Units
- `VSSTAT` (String): Completion Status
- `VSLOC` (String): Location of Vital Signs Measurement
- `VSBLFL` (String): Baseline Flag
- `VISITNUM` (Float64): Visit Number
- `VISIT` (String): Visit Name
- `VISITDY` (Float64): Planned Study Day of Visit
- `EPOCH` (String): Epoch
- `VSDTC` (String): Date/Time of Measurements
- `VSDY` (Float64): Study Day of Vital Signs
- `VSTPT` (String): Planned Time Point Name
- `VSTPTNUM` (Float64): Planned Time Point Number
- `VSELTM` (String): Planned Elapsed Time from Time Point Ref
- `VSTPTREF` (String): Time Point Reference
"""
vs_meta: Final[DatasetMeta]
